
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x0C
    
- platform: template
  name: "Source"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x38
    
- platform: template
  name: "1"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x01
    
- platform: template
  name: "2"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x02
    
- platform: template
  name: "3"
  on_press:
    - remote_transmitter.transmit_raw:
        carrier_frequency: 38kHz
        code: [690, -894, 1771, -890, 921, -890, 890, -894, 896, -887, 893, -1826, 1714, -918, 892, -891, 889, -894, 896, -1824, 831, -893, 887, -89510, 608, -843, 1771, -918, 943, -839, 941, -842, 938, -844, 946, -1827, 1652, -926, 935, -847, 943, -839, 941, -1805, 799, -898, 882, -81235, 195]
    
- platform: template
  name: "4"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x04
    
- platform: template
  name: "5"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x05
    
- platform: template
  name: "6"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x06
    
- platform: template
  name: "7"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x07
    
- platform: template
  name: "8"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x08
    
- platform: template
  name: "9"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x09
    
- platform: template
  name: "0"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x00
    
- platform: template
  name: "Language"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x0F
    
- platform: template
  name: "Txt"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x3C
    
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x10
    
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x11
    
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x0D
    
- platform: template
  name: "Home"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x30
    
- platform: template
  name: "Ch_next"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x20
    
- platform: template
  name: "Ch_prev"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x21
    
- platform: template
  name: "Guide"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x2F
    
- platform: template
  name: "Info"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x12
    
- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x14
    
- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x15
    
- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x16
    
- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x13
    
- platform: template
  name: "Ok"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x35
    
- platform: template
  name: "Back"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x0A
    
- platform: template
  name: "Exit"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x25
    
- platform: template
  name: "Rew"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x1B
    
- platform: template
  name: "Pause"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x31
    
- platform: template
  name: "Fw"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x1C
    
- platform: template
  name: "Rec"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x33
    
- platform: template
  name: "Play"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x19
    
- platform: template
  name: "Stop"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x18
    
- platform: template
  name: "Red"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x37
    
- platform: template
  name: "Green"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x36
    
- platform: template
  name: "Yelow"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x32
    
- platform: template
  name: "Blue"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x34
    