
- platform: template
  name: "On"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xFC03
        
- platform: template
  name: "Off"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xFD02
        
- platform: template
  name: "Brightness_Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xFE01
        
- platform: template
  name: "Brightness_Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xFF00
        
- platform: template
  name: "White"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF807
        
- platform: template
  name: "Blue"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF906
        
- platform: template
  name: "Green"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xFA05
        
- platform: template
  name: "Red"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xFB04
        
- platform: template
  name: "Flash"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF40B
        
- platform: template
  name: "Strobe"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF00F
        
- platform: template
  name: "Fade"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xEC13
        
- platform: template
  name: "Holiday"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xE817
        
- platform: template
  name: "Lighter_blue"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF50A
        
- platform: template
  name: "Purple"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF10E
        
- platform: template
  name: "Violet"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xED12
        
- platform: template
  name: "Pink"
  on_press:
    - remote_transmitter.transmit_raw:
        carrier_frequency: 38kHz
        code: [9202, -4458, 613, -525, 615, -524, 615, -524, 614, -525, 639, -502, 635, -505, 611, -556, 609, -531, 608, -1636, 608, -1636, 609, -1636, 607, -1635, 609, -531, 608, -1635, 610, -1635, 609, -1635, 608, -531, 608, -1635, 606, -1635, 608, -531, 608, -1635, 608, -531, 606, -531, 606, -531, 606, -1636, 582, -557, 609, -531, 608, -1637, 607, -532, 607, -1636, 607, -1636, 583, -1661, 584, -40805, 9182, -2206, 607, -95736, 9186, -2187, 629, -95752, 9256, -2185, 630, -95630, 9232, -2185, 629]
    
- platform: template
  name: "Lime_Green"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF609
        
- platform: template
  name: "Cyan"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF20D
        
- platform: template
  name: "Lighter_Cyan"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xEE11
        
- platform: template
  name: "Turquoise"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xEA15
        
- platform: template
  name: "Lighter_red"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF708
        
- platform: template
  name: "India_Red"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF30C
        
- platform: template
  name: "Orange"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xEF10
        
- platform: template
  name: "Yellow"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xEB14
        