
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xEF10
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xE51A
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xF10E
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xE916
        
- platform: template
  name: "Direct"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xF50A
        
- platform: template
  name: "Optical"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xF40B
        
- platform: template
  name: "Coax"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xF30C
        
- platform: template
  name: "Effect"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xE21D
        
- platform: template
  name: "Setting"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xE01F
        
- platform: template
  name: "Sub_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xFC03
        
- platform: template
  name: "Sub_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xFE01
        
- platform: template
  name: "Center_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xFD02
        
- platform: template
  name: "Center_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xF906
        
- platform: template
  name: "Surround_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xFF00
        
- platform: template
  name: "Surround_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xFB04
        
- platform: template
  name: "Testing"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xFA05
        