
- platform: template
  name: "POWER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xE51A
        
- platform: template
  name: "MODE"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFE01
        
- platform: template
  name: "BRZ_MODE"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF609
        
- platform: template
  name: "SWING"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFC03
        
- platform: template
  name: "TIMER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF807
        