
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xDF20
        command: 0xF30C
        
- platform: template
  name: "Source"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xDF20
        command: 0xE817
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xDF20
        command: 0xF708
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xDF20
        command: 0xEB14
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xDF20
        command: 0xFD02
        
- platform: template
  name: "Aux"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xDF20
        command: 0xE916
        
- platform: template
  name: "Line in"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xDF20
        command: 0xF00F
        