
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x540C
        nbits: 15

- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x240C
        nbits: 15

- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x640C
        nbits: 15

- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x140C
        nbits: 15

- platform: template
  name: "Input"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x4B0D
        nbits: 15
