
- platform: template
  name: "POWER_ON"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xFE01
        
- platform: template
  name: "POWER_OFF"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xFD02
        
- platform: template
  name: "INPUT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xFC03
        
- platform: template
  name: "VIDEO"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xFA05
        
- platform: template
  name: "VIDEO"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xF906
        
- platform: template
  name: "RGB"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xF708
        
- platform: template
  name: "RGB2:_D-SUB15"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xF609
        
- platform: template
  name: "RGB3:_5_BNC"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xF50A
        
- platform: template
  name: "S-VIDEO"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xF40B
        
- platform: template
  name: "COMPONENT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xF30C
        
- platform: template
  name: "RGB1:_DVI-D"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xF10E
        
- platform: template
  name: "SHIFT_1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xEF10
        
- platform: template
  name: "VOLUME_UP"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xDF20
        
- platform: template
  name: "SHIFT_2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xDF20
        
- platform: template
  name: "VOL_+"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xDF20
        
- platform: template
  name: "VOLUME_DOWN"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xDE21
        
- platform: template
  name: "VOL_-"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xDE21
        
- platform: template
  name: "SHIFT_3"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xCF30
        
- platform: template
  name: "ARROW_LEFT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xC13E
        
- platform: template
  name: "ADJ_LEFT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xC13E
        
- platform: template
  name: "ARROW_RIGHT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xC03F
        
- platform: template
  name: "ADJ_RIGHT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xC03F
        
- platform: template
  name: "MENU"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xBF40
        
- platform: template
  name: "SHIFT_4"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xBF40
        
- platform: template
  name: "ARROW_UP"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xBE41
        
- platform: template
  name: "ADJ_UP"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xBE41
        
- platform: template
  name: "ARROW_DOWN"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xBD42
        
- platform: template
  name: "ADJ_DOWN"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xBD42
        
- platform: template
  name: "ENTER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xA45B
        
- platform: template
  name: "SET"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xA45B
        
- platform: template
  name: "WIDE"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0x7F80
        
- platform: template
  name: "ASPECT_TOGGLE"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0x7F80
        
- platform: template
  name: "ASPECT_AUTO"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0x7E81
        
- platform: template
  name: "ASPECT_NORMAL"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0x7D82
        
- platform: template
  name: "ASPECT_WIDE1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0x7C83
        
- platform: template
  name: "ASPECT_WIDE2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0x7B84
        
- platform: template
  name: "ASPECT_ZOOM1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0x7A85
        
- platform: template
  name: "ASPECT_ZOOM2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0x7986
        
- platform: template
  name: "LOCK_(HIDDEN)"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0x1FE0
        
- platform: template
  name: "MODE_(HIDDEN)"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0x05FA
        