
- platform: template
  name: "MENU"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBF40
        
- platform: template
  name: "UP"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB946
        
- platform: template
  name: "DOWN"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xEA15
        
- platform: template
  name: "LEFT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBB44
        
- platform: template
  name: "RIGHT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBC43
        
- platform: template
  name: "ZOOM_UP"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBA45
        
- platform: template
  name: "ZOOM_DOWN"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB847
        
- platform: template
  name: "AE"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF609
        
- platform: template
  name: "VERT_MIRR"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF807
        
- platform: template
  name: "HOR_MIRR"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE916
        
- platform: template
  name: "COLOR"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF30C
        
- platform: template
  name: "FREEZE"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE718
        
- platform: template
  name: "PLAY_PAUSE"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xA15E
        
- platform: template
  name: "PICTURE"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF708
        
- platform: template
  name: "VIDEO"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE31C
        
- platform: template
  name: "VIDEO_MODE"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xA55A
        