
- platform: template
  name: "Play_Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBA45
        
- platform: template
  name: "Bluetooth"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBC43
        
- platform: template
  name: "Light"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB847
        
- platform: template
  name: "Prev"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBB44
        
- platform: template
  name: "Next"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBF40
        
- platform: template
  name: "Timer"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB946
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF807
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE31C
        
- platform: template
  name: "Clock"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF20D
        
- platform: template
  name: "Usb"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE619
        
- platform: template
  name: "Alarm"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF609
        
- platform: template
  name: "Sleep_helper"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE916
        
- platform: template
  name: "Waves"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF30C
        
- platform: template
  name: "Bugs"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE718
        
- platform: template
  name: "Bonfire"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xA15E
        
- platform: template
  name: "White_noise"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF30C
        
- platform: template
  name: "Rain"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xEA15
        
- platform: template
  name: "Stream"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB54A
        
- platform: template
  name: "Wind"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF708
        
- platform: template
  name: "Lullaby"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xAD52
        
- platform: template
  name: "Bird"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xA55A
        