
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xE51A
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFE01
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFC03
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF906
        
- platform: template
  name: "OPT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF30C
        
- platform: template
  name: "USB"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xED12
        
- platform: template
  name: "AUX"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF10E
        
- platform: template
  name: "PHONO"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF00F
        
- platform: template
  name: "LED"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xE01F
        
- platform: template
  name: "SUB-"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xC23D
        
- platform: template
  name: "SUB+"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFC03
        
- platform: template
  name: "SUB_RESET"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xC13E
        
- platform: template
  name: "PLAY_PAUSE"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xDE21
        
- platform: template
  name: "BLUETOOTH"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF20D
        