
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xE51A
        
- platform: template
  name: "Play_pause"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xDE21
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFC03
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF906
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFE01
        
- platform: template
  name: "Sub_down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xC23D
        
- platform: template
  name: "Sub_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xC33C
        
- platform: template
  name: "Sub_reset"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xC13E
        
- platform: template
  name: "Tv"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xE619
        
- platform: template
  name: "Bt"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF20D
        
- platform: template
  name: "Aux"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF10E
        
- platform: template
  name: "Phono"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF00F
        
- platform: template
  name: "Opt"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF30C
        
- platform: template
  name: "Usb"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xED12
        