
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x57A8
        
- platform: template
  name: "Projection"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x29D6
        
- platform: template
  name: "Input"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x6897
        
- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x6A95
        
- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x659A
        
- platform: template
  name: "OK"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x619E
        
- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x649B
        
- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x6699
        
- platform: template
  name: "Menu"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x6E91
        
- platform: template
  name: "Back"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x5BA4
        
- platform: template
  name: "Play/Pause"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x6C93
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x7788
        
- platform: template
  name: "VOL+"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x738C
        
- platform: template
  name: "VOL-"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x639C
        
- platform: template
  name: "Next"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x7D82
        
- platform: template
  name: "Prev"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x6798
        