
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFC03
        
- platform: template
  name: "HDMI_1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFB04
        
- platform: template
  name: "HDMI_2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF609
        