
- platform: template
  name: "Power_on"
  on_press:
    - remote_transmitter.transmit_raw:
        carrier_frequency: 38kHz
        code: [962, -776, 1829, -1696, 938, -827, 743]
    
- platform: template
  name: "Power_off"
  on_press:
    - remote_transmitter.transmit_raw:
        carrier_frequency: 38kHz
        code: [933, -864, 1850, -1673, 933, -831, 910, -856, 937]
    
- platform: template
  name: "Brightness_up"
  on_press:
    - remote_transmitter.transmit_raw:
        carrier_frequency: 38kHz
        code: [966, -800, 1856, -1666, 965, -798, 963, -800, 1213]
    
- platform: template
  name: "Brightness_dn"
  on_press:
    - remote_transmitter.transmit_raw:
        carrier_frequency: 38kHz
        code: [992, -776, 1826, -1697, 935, -827, 962, -800, 1410]
    
- platform: template
  name: "Auto"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x1D
        command: 0x38
    
- platform: template
  name: "Set"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x1D
        command: 0x37
    