
- platform: template
  name: "POWER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xE11E
        
- platform: template
  name: "Timer 0h"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFE01
        
- platform: template
  name: "Timer 2h"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFD02
        
- platform: template
  name: "Timer 4h"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFC03
        
- platform: template
  name: "Audio"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xED12
        
- platform: template
  name: "Light"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xE51A
        
- platform: template
  name: "+"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xE41B
        
- platform: template
  name: "-"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF20D
        
- platform: template
  name: "Fan 1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFB04
        
- platform: template
  name: "Fan 2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFA05
        
- platform: template
  name: "Fan 3"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF906
        
- platform: template
  name: "Fan OFF"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF708
        
- platform: template
  name: "50 C"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF807
        
- platform: template
  name: "100 C"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF609
        
- platform: template
  name: "200 C"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF50A
        
- platform: template
  name: "210 C"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xE01F
        
- platform: template
  name: "220 C"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF30C
        
- platform: template
  name: "230 C"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF10E
        