
- platform: template
  name: "On_dvd"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE780
        command: 0xE718
        
- platform: template
  name: "On_video"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE780
        command: 0xED12
        
- platform: template
  name: "Option"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE780
        command: 0xEE11
        
- platform: template
  name: "Off"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE780
        command: 0xF30C
        
- platform: template
  name: "Chapter_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE780
        command: 0xF50A
        
- platform: template
  name: "Track_down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE780
        command: 0xF40B
        
- platform: template
  name: "Folder_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE780
        command: 0xB14E
        
- platform: template
  name: "Folder_down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE780
        command: 0xB04F
        
- platform: template
  name: "Enter"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE780
        command: 0xD728
        
- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE780
        command: 0xDF20
        
- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE780
        command: 0xDD22
        
- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE780
        command: 0xDC23
        
- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE780
        command: 0xDE21
        
- platform: template
  name: "Play_pause"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE780
        command: 0xE11E
        
- platform: template
  name: "Back"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE780
        command: 0xE31C
        
- platform: template
  name: "Forward"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE780
        command: 0xE01F
        
- platform: template
  name: "Stop"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE780
        command: 0xE21D
        
- platform: template
  name: "Top_menu"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE780
        command: 0xE51A
        
- platform: template
  name: "Menu"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE780
        command: 0xE619
        
- platform: template
  name: "Set_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE780
        command: 0xBE41
        
- platform: template
  name: "Search"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE780
        command: 0xBA45
        
- platform: template
  name: "Sub_title"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE780
        command: 0xBD42
        
- platform: template
  name: "Audio"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE780
        command: 0xBC43
        
- platform: template
  name: "Angle"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE780
        command: 0xBB44
        
- platform: template
  name: "Size"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE780
        command: 0xE916
        
- platform: template
  name: "Display"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE780
        command: 0xEA15
        