
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBA45
        
- platform: template
  name: "Aurora PWR"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB946
        
- platform: template
  name: "Stars PWR"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB847
        
- platform: template
  name: "Aurora Red"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBB44
        
- platform: template
  name: "Aurora Green"
  on_press:
    - remote_transmitter.transmit_raw:
        carrier_frequency: 38kHz
        code: [1072098130, -526, 524, -614, 1777, -1636, 1586, -613, 1664, -586, 1637, -613, 1638, -612, 1636, -614, 1636, -614, 1638, -612, 1636, -614, 1664, -638, 472, -666, 473, -613, 525, -613, 524, -614, 1637, -665, 475, -611, 522, -616, 524, -614, 1636, -666, 1584, -615, 1637, -613, 1636, -614, 526, -612, 1635, -615, 40102, -9095, 2241, -614]
    
- platform: template
  name: "Aurora Blue"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE916
        
- platform: template
  name: "Aurora White"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF20D
        
- platform: template
  name: "Mode"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF30C
        
- platform: template
  name: "Bright UP"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE718
        
- platform: template
  name: "Bright DWN"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE31C
        
- platform: template
  name: "Speed UP"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xA15E
        
- platform: template
  name: "Speed DWN"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xA55A
        
- platform: template
  name: "Time 1 Hour"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xAD52
        
- platform: template
  name: "Time 2 Hours"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB54A
        
- platform: template
  name: "BT Mode"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBD42
        
- platform: template
  name: "Voice Mode"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF708
        
- platform: template
  name: "Vol UP"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBF40
        
- platform: template
  name: "Vol DWN"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE619
        
- platform: template
  name: "Previous"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF807
        
- platform: template
  name: "Next"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF609
        
- platform: template
  name: "Play_Pause"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xEA15
        