
- platform: template
  name: "ON"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xFA05
        
- platform: template
  name: "OFF"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xFB04
        
- platform: template
  name: "BRIGHT UP"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xFD02
        
- platform: template
  name: "WHOLE LIGHT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xFE01
        
- platform: template
  name: "COLD"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xF807
        
- platform: template
  name: "DIM"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xF906
        
- platform: template
  name: "NIGHT LIGHT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xF708
        
- platform: template
  name: "TIMER 30 MIN"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xF609
        
- platform: template
  name: "W ww"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xEF10
        
- platform: template
  name: "WARM"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xFC03
        