
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB54A
        
- platform: template
  name: "Speed"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBD42
        
- platform: template
  name: "Light"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xAD52
        
- platform: template
  name: "Timer"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB649
        
- platform: template
  name: "Turn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBF40
        
- platform: template
  name: "Cool"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBB44
        
- platform: template
  name: "M"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB946
        