
- platform: template
  name: "Sleep"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD00
        command: 0xFE01
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD00
        command: 0xFC03
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD00
        command: 0xF609
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD00
        command: 0xF807
        