
- platform: template
  name: "On/Off"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE817
        
- platform: template
  name: "Line_01"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xA25D
        
- platform: template
  name: "Line_02"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE11E
        