
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF86
        command: 0xE31C
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF86
        command: 0xDE21
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF86
        command: 0xD42B
        
- platform: template
  name: "VolMute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF86
        command: 0xE21D
        
- platform: template
  name: "Ch_next"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF86
        command: 0xDE21
        
- platform: template
  name: "Ch_prev"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF86
        command: 0xD42B
        
- platform: template
  name: "DPad_Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF86
        command: 0xDE21
        
- platform: template
  name: "DPad_Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF86
        command: 0xD42B
        
- platform: template
  name: "DPad_Left"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF86
        command: 0xEC13
        
- platform: template
  name: "DPad_Right"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF86
        command: 0xEB14
        
- platform: template
  name: "Rewind"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF86
        command: 0xEC13
        
- platform: template
  name: "Play"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF86
        command: 0xD52A
        
- platform: template
  name: "FastForward"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF86
        command: 0xEB14
        
- platform: template
  name: "Pause"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF86
        command: 0xD52A
        
- platform: template
  name: "Stop"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF86
        command: 0xD52A
        
- platform: template
  name: "Skip_Back"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF86
        command: 0xEC13
        
- platform: template
  name: "Skip_Forward"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF86
        command: 0xEB14
        
- platform: template
  name: "Guide"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF86
        command: 0xD52A
        
- platform: template
  name: "Info"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF86
        command: 0xD42B
        
- platform: template
  name: "InputAux"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF86
        command: 0xEF10
        
- platform: template
  name: "InputBluetooth"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF86
        command: 0xE41B
        
- platform: template
  name: "InputOptical"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF86
        command: 0xED12
        
- platform: template
  name: "InputUSB"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF86
        command: 0xD629
        
- platform: template
  name: "Movie"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF86
        command: 0xD32C
        
- platform: template
  name: "Music"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF86
        command: 0xD827
        
- platform: template
  name: "News"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF86
        command: 0xD22D
        
- platform: template
  name: "Pair"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF86
        command: 0xD52A
        