
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xAA55
        
- platform: template
  name: "Sleep timer"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xEC13
        
- platform: template
  name: "Fan +"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xD827
        
- platform: template
  name: "Fan -"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB54A
        
- platform: template
  name: "Oscillation +"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xA659
        
- platform: template
  name: "Oscillation -"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x9768
        
- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE31C
        
- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xCB34
        