
- platform: template
  name: "POWER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xED12
        
- platform: template
  name: "FIRE+"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xE51A
        
- platform: template
  name: "FIRE-"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xFA05
        
- platform: template
  name: "FUEL+"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xE21D
        
- platform: template
  name: "FUEL-"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xE619
        
- platform: template
  name: "TEMP+"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xE718
        
- platform: template
  name: "TEMP-"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xE01F
        
- platform: template
  name: "TIMER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xE31C
        
- platform: template
  name: "SOUND"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xE11E
        