
- platform: template
  name: "STANDBY"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x7F80
        
- platform: template
  name: "OPEN/CLOSE"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x7E81
        
- platform: template
  name: "PLAY"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x7D82
        
- platform: template
  name: "PAUSE"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x7C83
        
- platform: template
  name: "STOP"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x7A85
        
- platform: template
  name: "SEARCH_-"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x7986
        
- platform: template
  name: "SEARCH_+"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x7887
        
- platform: template
  name: "SLOW_-"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x718E
        
- platform: template
  name: "SLOW_+"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x708F
        
- platform: template
  name: "0"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x6C93
        
- platform: template
  name: "1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x6B94
        
- platform: template
  name: "2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x6A95
        
- platform: template
  name: "3"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x6996
        
- platform: template
  name: "4"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x6897
        
- platform: template
  name: "5"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x6798
        
- platform: template
  name: "6"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x6699
        
- platform: template
  name: "7"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x659A
        
- platform: template
  name: "8"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x649B
        
- platform: template
  name: "9"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x639C
        
- platform: template
  name: "SEARCH"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x619E
        
- platform: template
  name: "CLEAR"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x609F
        
- platform: template
  name: "PROGRAM"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x5FA0
        
- platform: template
  name: "REPEAT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x5CA3
        
- platform: template
  name: "A/B"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x5BA4
        
- platform: template
  name: "ON_SCREEN"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x59A6
        
- platform: template
  name: "STATUS"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x57A8
        
- platform: template
  name: "SUB_TITLE"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x57A8
        
- platform: template
  name: "SETUP"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x53AC
        
- platform: template
  name: "AUDIO"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x52AD
        
- platform: template
  name: "ANGLE"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x51AE
        
- platform: template
  name: "TOP_MENU"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x4EB1
        
- platform: template
  name: "CURSOR_DOWN"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x4CB3
        
- platform: template
  name: "CURSOR_UP"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x4BB4
        
- platform: template
  name: "CURSOR_LEFT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x4AB5
        
- platform: template
  name: "CURSOR_RIGHT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x49B6
        
- platform: template
  name: "RETURN"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x48B7
        
- platform: template
  name: "CURSOR_ENTER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x47B8
        
- platform: template
  name: "SKIP_-"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x46B9
        
- platform: template
  name: "SKIP_+"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x45BA
        
- platform: template
  name: "POP_UP_MENU"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x30CF
        
- platform: template
  name: "ZOOM"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x28D7
        
- platform: template
  name: "DIGEST"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x1DE2
        
- platform: template
  name: "RED"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x16E9
        
- platform: template
  name: "GREEN"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x15EA
        
- platform: template
  name: "MARKER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x15EA
        
- platform: template
  name: "BLUE"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x14EB
        
- platform: template
  name: "YELLOW"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x13EC
        
- platform: template
  name: "PIP"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x12ED
        
- platform: template
  name: "2ND_AUDIO"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x11EE
        
- platform: template
  name: "HOME"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x10EF
        
- platform: template
  name: "REPEAT_OFF"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x0CF3
        
- platform: template
  name: "POWER_ON"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x09F6
        
- platform: template
  name: "POWER_OFF"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x007C
        command: 0x08F7
        