
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xEF10
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xE51A
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xF10E
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xE916
        
- platform: template
  name: "Stereo1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xEC13
        
- platform: template
  name: "Stereo2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xE41B
        
- platform: template
  name: "Stereo3"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xE718
        
- platform: template
  name: "Optical1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xEE11
        
- platform: template
  name: "Optical2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xE619
        
- platform: template
  name: "Coax"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xF30C
        
- platform: template
  name: "Effect"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xE21D
        
- platform: template
  name: "Settings"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xE01F
        
- platform: template
  name: "Sub_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xFC03
        
- platform: template
  name: "Sub_down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xFE01
        
- platform: template
  name: "Centre_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xFD02
        
- platform: template
  name: "Centre_down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xF906
        
- platform: template
  name: "Surround_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xFF00
        
- platform: template
  name: "Surround_down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xFB04
        