
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFC03
        
- platform: template
  name: "Fan_Speed"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xA35C
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xAC53
        