
- platform: template
  name: "Menu"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x87EE
        command: 0xFD02
        
- platform: template
  name: "Play_Pause"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x87EE
        command: 0xA15E
        
- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x87EE
        command: 0xF40B
        
- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x87EE
        command: 0xF20D
        
- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x87EE
        command: 0xF708
        
- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x87EE
        command: 0xF807
        
- platform: template
  name: "Center"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x87EE
        command: 0xA25D
        
- platform: template
  name: "Reboot"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x87EE
        command: 0xE718
        