
- platform: template
  name: "On"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFE01
        
- platform: template
  name: "Off"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFF00
        
- platform: template
  name: "2h"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF30C
        
- platform: template
  name: "4h"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF609
        
- platform: template
  name: "6h"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF50A
        
- platform: template
  name: "8h"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xEA15
        
- platform: template
  name: "Flicker"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF20D
        
- platform: template
  name: "Steady"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE916
        
- platform: template
  name: "Dim"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF10E
        
- platform: template
  name: "Brighten"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xEB14
        