
- platform: template
  name: "POWER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xED12
        
- platform: template
  name: "OK"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xBB44
        
- platform: template
  name: "UP"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xE01F
        
- platform: template
  name: "DOWN"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xBE41
        
- platform: template
  name: "RIGHT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xF609
        
- platform: template
  name: "LEFT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xF00F
        
- platform: template
  name: "HOME"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xFD02
        
- platform: template
  name: "VOL-"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xF906
        
- platform: template
  name: "VOL+"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xFF00
        
- platform: template
  name: "AUTOFOCUS"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xFC03
        
- platform: template
  name: "BACK"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xAF50
        
- platform: template
  name: "LIST"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xEC13
        