
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x91C8
        command: 0xFF00
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x91C8
        command: 0xDF20
        
- platform: template
  name: "Moon"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x91C8
        command: 0x8E71
        
- platform: template
  name: "Tv_ARC"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x91C8
        command: 0xF00F
        
- platform: template
  name: "OPT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x91C8
        command: 0xF10E
        
- platform: template
  name: "AUX"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x91C8
        command: 0xF20D
        
- platform: template
  name: "Main_Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x91C8
        command: 0xE11E
        
- platform: template
  name: "Main_Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x91C8
        command: 0xE01F
        
- platform: template
  name: "Bass_Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x91C8
        command: 0xA35C
        
- platform: template
  name: "Bas_Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x91C8
        command: 0xA25D
        
- platform: template
  name: "Voice_Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x91C8
        command: 0x956A
        
- platform: template
  name: "Voice_Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x91C8
        command: 0x946B
        
- platform: template
  name: "Back"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x91C8
        command: 0xD926
        
- platform: template
  name: "Pause"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x91C8
        command: 0xDE21
        
- platform: template
  name: "Forward"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x91C8
        command: 0xDB24
        
- platform: template
  name: "Cinema"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x91C8
        command: 0x8877
        
- platform: template
  name: "Sports"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x91C8
        command: 0x8679
        
- platform: template
  name: "Music"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x91C8
        command: 0x8778
        