
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xFB04
        
- platform: template
  name: "Speed"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xF906
        
- platform: template
  name: "Temp+"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xFA05
        
- platform: template
  name: "Temp-"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xFE01
        
- platform: template
  name: "Mode"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xF20D
        
- platform: template
  name: "Timer"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xFF00
        