
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_pronto:
        d

- platform: template
  name: "Eject"
  on_press:
    - remote_transmitter.transmit_pronto:
        d

- platform: template
  name: "Prev"
  on_press:
    - remote_transmitter.transmit_pronto:
        d

- platform: template
  name: "Ok"
  on_press:
    - remote_transmitter.transmit_pronto:
        d

- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_pronto:
        d

- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_pronto:
        d

- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_pronto:
        d

- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_pronto:
        d

- platform: template
  name: "Fast_fo"
  on_press:
    - remote_transmitter.transmit_pronto:
        d

- platform: template
  name: "Fast_ba"
  on_press:
    - remote_transmitter.transmit_pronto:
        d

- platform: template
  name: "Pause"
  on_press:
    - remote_transmitter.transmit_pronto:
        d

- platform: template
  name: "Play"
  on_press:
    - remote_transmitter.transmit_pronto:
        d

- platform: template
  name: "Stop"
  on_press:
    - remote_transmitter.transmit_pronto:
        d

- platform: template
  name: "Subtitle"
  on_press:
    - remote_transmitter.transmit_pronto:
        d

- platform: template
  name: "Home"
  on_press:
    - remote_transmitter.transmit_pronto:
        d

- platform: template
  name: "Netflix"
  on_press:
    - remote_transmitter.transmit_pronto:
        d

- platform: template
  name: "Audio"
  on_press:
    - remote_transmitter.transmit_pronto:
        d

- platform: template
  name: "Top_menu"
  on_press:
    - remote_transmitter.transmit_pronto:
        d

- platform: template
  name: "PopUp"
  on_press:
    - remote_transmitter.transmit_pronto:
        d

- platform: template
  name: "Exit"
  on_press:
    - remote_transmitter.transmit_pronto:
        d
