
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x57B8
        command: 0xF30C
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x57B8
        command: 0xF20D
        
- platform: template
  name: "Fast Forward"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x57B8
        command: 0xE21D
        
- platform: template
  name: "Fast Rewind"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x57B8
        command: 0xE31C
        
- platform: template
  name: "Play"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x57B8
        command: 0xE718
        
- platform: template
  name: "OK"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x57B8
        command: 0xED12
        
- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x57B8
        command: 0xEE11
        
- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x57B8
        command: 0xEC13
        
- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x57B8
        command: 0xEF10
        
- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x57B8
        command: 0xEB14
        
- platform: template
  name: "Source"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x57B8
        command: 0xF10E
        
- platform: template
  name: "Menu"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x57B8
        command: 0xE916
        
- platform: template
  name: "Exit"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x57B8
        command: 0xE817
        
- platform: template
  name: "Volume Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x57B8
        command: 0xE11E
        
- platform: template
  name: "Volume Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x57B8
        command: 0xE01F
        