
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xC7EA
        command: 0xE817
        
- platform: template
  name: "Home"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xC7EA
        command: 0xFC03
        
- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xC7EA
        command: 0xE11E
        
- platform: template
  name: "Select"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xC7EA
        command: 0xD52A
        
- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xC7EA
        command: 0xD22D
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xC7EA
        command: 0xDF20
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xC7EA
        command: 0xF00F
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xC7EA
        command: 0xEF10
        