
- platform: template
  name: "1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFD02
        
- platform: template
  name: "2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFB04
        
- platform: template
  name: "3"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF906
        
- platform: template
  name: "Next"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF708
        