
- platform: template
  name: "Back"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFB04
        
- platform: template
  name: "Next"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFD02
        
- platform: template
  name: "Rep"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFA05
        
- platform: template
  name: "Play"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFF00
        
- platform: template
  name: "Stop"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFE01
        