
- platform: template
  name: "POWER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xF708
        
- platform: template
  name: "Input"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xF40B
        
- platform: template
  name: "Ok"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xBB44
        
- platform: template
  name: "Chanel_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xFF00
        
- platform: template
  name: "Channel_down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xFE01
        
- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xBF40
        
- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xBE41
        
- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xF807
        
- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xF906
        
- platform: template
  name: "MUTE"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xF609
        
- platform: template
  name: "Volume_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xFD02
        
- platform: template
  name: "Volume_down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xFC03
        
- platform: template
  name: "Surr_POWER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xEF10
        
- platform: template
  name: "Surr_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xE51A
        
- platform: template
  name: "Surr_down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xF10E
        
- platform: template
  name: "Surr_mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xE916
        