
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x857A
        command: 0xE51A
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x857A
        command: 0xE41B
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x857A
        command: 0xE31C
        
- platform: template
  name: "HDMI_1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x857A
        command: 0xB847
        
- platform: template
  name: "HDMI_2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x857A
        command: 0xB54A
        
- platform: template
  name: "HDMI_3"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x857A
        command: 0xB24D
        
- platform: template
  name: "HDMI_4"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x857A
        command: 0xAF50
        
- platform: template
  name: "HDMI_5"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x857A
        command: 0x8F70
        
- platform: template
  name: "HDMI_6"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x857A
        command: 0x8C73
        
- platform: template
  name: "HDMI_7"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x857A
        command: 0x6798
        
- platform: template
  name: "V_AUX"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x857A
        command: 0xAA55
        
- platform: template
  name: "AV_1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x857A
        command: 0xAC53
        
- platform: template
  name: "AV_2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x857A
        command: 0xA956
        
- platform: template
  name: "Phono"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x857A
        command: 0xEB14
        
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x817E
        command: 0xD52A
        