
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xF50A
        
- platform: template
  name: "1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xEE11
        
- platform: template
  name: "2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xED12
        
- platform: template
  name: "3"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xEC13
        
- platform: template
  name: "4"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xEB14
        
- platform: template
  name: "5"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xEA15
        
- platform: template
  name: "6"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xE916
        
- platform: template
  name: "7"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xE817
        
- platform: template
  name: "8"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xE718
        
- platform: template
  name: "9"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xE619
        
- platform: template
  name: "Favorite"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xBE41
        
- platform: template
  name: "0"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xEF10
        
- platform: template
  name: "Groups"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xAC53
        
- platform: template
  name: "Red"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xB44B
        
- platform: template
  name: "Green"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xB54A
        
- platform: template
  name: "Yellow"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xB649
        
- platform: template
  name: "Blue"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xB748
        
- platform: template
  name: "Info"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xF906
        
- platform: template
  name: "Guide"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xF708
        
- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xFF00
        
- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xFE01
        
- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xFC03
        
- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xFD02
        
- platform: template
  name: "Ok"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xE01F
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xB14E
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xB04F
        
- platform: template
  name: "Ch_next"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xA15E
        
- platform: template
  name: "Ch_prev"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xA05F
        
- platform: template
  name: "Back"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0x728D
        
- platform: template
  name: "Home"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0x9A65
        
- platform: template
  name: "Menu"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xFB04
        
- platform: template
  name: "Play/Pause"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xF807
        
- platform: template
  name: "Record"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0xA956
        
- platform: template
  name: "2dots"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0x758A
        
- platform: template
  name: "3dots"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0x7887
        
- platform: template
  name: "4dots"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF902
        command: 0x7986
        