
- platform: template
  name: "POWER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBA45
        
- platform: template
  name: "TEMP+"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xEA15
        
- platform: template
  name: "TEMP-"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE718
        
- platform: template
  name: "Mode"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB847
        
- platform: template
  name: "Timer"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xAD52
        
- platform: template
  name: "Units_Toggle"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE817
        