
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x686C
        command: 0xA956
        
- platform: template
  name: "Display"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x686C
        command: 0xAB54
        
- platform: template
  name: "Rewind"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x686C
        command: 0xBE41
        
- platform: template
  name: "Play_Pause"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x686C
        command: 0xE718
        
- platform: template
  name: "Forward"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x686C
        command: 0xE817
        
- platform: template
  name: "Back"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x686C
        command: 0xE619
        
- platform: template
  name: "Stop"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x686C
        command: 0xFB04
        
- platform: template
  name: "Skip"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x686C
        command: 0xEC13
        
- platform: template
  name: "Home"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x686C
        command: 0xBF40
        
- platform: template
  name: "Return"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x686C
        command: 0xBB44
        
- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x686C
        command: 0xA15E
        
- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x686C
        command: 0xA758
        
- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x686C
        command: 0xA05F
        
- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x686C
        command: 0xA35C
        
- platform: template
  name: "Ok"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x686C
        command: 0xA25D
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x686C
        command: 0xE41B
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x686C
        command: 0xB34C
        
- platform: template
  name: "Setup"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x686C
        command: 0xBA45
        
- platform: template
  name: "Mode"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x686C
        command: 0xB649
        
- platform: template
  name: "Audio"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x686C
        command: 0xFA05
        
- platform: template
  name: "Subtitle"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x686C
        command: 0xA45B
        
- platform: template
  name: "Language"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x686C
        command: 0xA857
        
- platform: template
  name: "Repeat"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x686C
        command: 0xA55A
        
- platform: template
  name: "Zoom"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x686C
        command: 0xBD42
        