
- platform: template
  name: "On-Off"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFF00
        
- platform: template
  name: "Display"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFD02
        
- platform: template
  name: "Mist"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF708
        
- platform: template
  name: "Auto"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF609
        
- platform: template
  name: "Sleep"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF50A
        
- platform: template
  name: "Humidity"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xEF10
        
- platform: template
  name: "Timer"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xED12
        