
- platform: template
  name: "Power_on_off"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xEB14
        
- platform: template
  name: "Flame_control"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xE21D
        
- platform: template
  name: "Heater_on_off"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xED12
        
- platform: template
  name: "Timer"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xE619
        
- platform: template
  name: "Temp_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xE51A
        
- platform: template
  name: "Temp_down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xFA05
        