
- platform: template
  name: "Manual"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF10A
        command: 0xF807
        
- platform: template
  name: "Red"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF10A
        command: 0xF609
        
- platform: template
  name: "Green"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF10A
        command: 0xF50A
        
- platform: template
  name: "Blue"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF10A
        command: 0xF40B
        
- platform: template
  name: "Amber"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF10A
        command: 0xE718
        
- platform: template
  name: "UV"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF10A
        command: 0xE619
        
- platform: template
  name: "White"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF10A
        command: 0xE51A
        
- platform: template
  name: "Plus"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF10A
        command: 0xF30C
        
- platform: template
  name: "Minus"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF10A
        command: 0xF10E
        
- platform: template
  name: "0"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF10A
        command: 0xF20D
        
- platform: template
  name: "1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF10A
        command: 0xF00F
        
- platform: template
  name: "2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF10A
        command: 0xEF10
        
- platform: template
  name: "3"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF10A
        command: 0xEE11
        
- platform: template
  name: "4"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF10A
        command: 0xED12
        
- platform: template
  name: "5"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF10A
        command: 0xEC13
        
- platform: template
  name: "6"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF10A
        command: 0xEB14
        
- platform: template
  name: "7"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF10A
        command: 0xEA15
        
- platform: template
  name: "8"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF10A
        command: 0xE916
        
- platform: template
  name: "9"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF10A
        command: 0xE817
        
- platform: template
  name: "Blackout"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF10A
        command: 0xFF00
        
- platform: template
  name: "Auto"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF10A
        command: 0xFE01
        
- platform: template
  name: "Speed"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF10A
        command: 0xFB04
        
- platform: template
  name: "Sound"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF10A
        command: 0xFD02
        
- platform: template
  name: "Strobe"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF10A
        command: 0xFC03
        
- platform: template
  name: "Sensitivity"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF10A
        command: 0xFA05
        
- platform: template
  name: "Fade"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF10A
        command: 0xF708
        
- platform: template
  name: "Percent"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xF10A
        command: 0xF906
        