
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xEF10
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xE817
        
- platform: template
  name: "Bt"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xB54A
        
- platform: template
  name: "Optical"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xB649
        
- platform: template
  name: "Line"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xB847
        
- platform: template
  name: "Usb"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xF50A
        
- platform: template
  name: "Reset"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xEC13
        