
- platform: template
  name: "POWER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBF40
        
- platform: template
  name: "MinMax"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFC03
        
- platform: template
  name: "ChildLock"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xA857
        
- platform: template
  name: "HumiLevel"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE817
        