
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_raw:
        carrier_frequency: 38kHz
        code: [9120, -4354, 714, -1539, 660, -497, 633, -499, 631, -500, 630, -503, 628, -503, 628, -503, 629, -503, 628, -503, 628, -1627, 628, -1627, 628, -1627, 628, -1627, 628, -1626, 628, -1627, 628, -1627, 628, -1627, 628, -1627, 628, -503, 628, -503, 628, -503, 628, -503, 628, -504, 627, -503, 628, -504, 627, -503, 628, -1627, 628, -1628, 627, -1628, 627, -1627, 628, -1627, 628, -1628, 627, -40094, 9038, -2194, 628]
    
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xFD02
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xEE11
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xEF10
        
- platform: template
  name: "Treble_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xF609
        
- platform: template
  name: "Treble_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xF20D
        
- platform: template
  name: "Bass_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xF50A
        
- platform: template
  name: "Bass_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xF10E
        
- platform: template
  name: "Play_pause"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xD32C
        
- platform: template
  name: "Prev"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xA55A
        
- platform: template
  name: "Next"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xA45B
        
- platform: template
  name: "Input"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xFB04
        
- platform: template
  name: "Reset"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xF708
        