
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xED12
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE01F
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF609
        
- platform: template
  name: "VolumeMute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE11E
        
- platform: template
  name: "PrevTrack"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFD02
        
- platform: template
  name: "Play_Pause"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF906
        
- platform: template
  name: "EQ"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFC03
        
- platform: template
  name: "MonoStereo"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFB04
        
- platform: template
  name: "Source"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFA05
        