
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xCD32
        command: 0xFD02
        
- platform: template
  name: "Power_off"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xCD32
        command: 0xD12E
        
- platform: template
  name: "Input"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xCD32
        command: 0xE718
        
- platform: template
  name: "Menu"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xCD32
        command: 0x7788
        
- platform: template
  name: "Info"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xCD32
        command: 0xDA25
        
- platform: template
  name: "Ok"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xCD32
        command: 0x3AC5
        
- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xCD32
        command: 0x39C6
        
- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xCD32
        command: 0x38C7
        
- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xCD32
        command: 0x37C8
        
- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xCD32
        command: 0x36C9
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xCD32
        command: 0xFC03
        
- platform: template
  name: "Mode"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xCD32
        command: 0x6A95
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xCD32
        command: 0xF609
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xCD32
        command: 0xF30C
        
- platform: template
  name: "Format"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xCD32
        command: 0xEA15
        
- platform: template
  name: "Freeze"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xCD32
        command: 0xF906
        