
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E040BF
        nbits: 32

- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E0E01F
        nbits: 32

- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E0D02F
        nbits: 32

- platform: template
  name: "Ch_next"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E048B7
        nbits: 32

- platform: template
  name: "Ch_prev"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E008F7
        nbits: 32

- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E0F00F
        nbits: 32
