
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E06798
        nbits: 32

- platform: template
  name: "Source"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E0807F
        nbits: 32

- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E006F9
        nbits: 32

- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E08679
        nbits: 32

- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E0A659
        nbits: 32

- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E046B9
        nbits: 32

- platform: template
  name: "Ok"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E016E9
        nbits: 32

- platform: template
  name: "Return"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E01AE5
        nbits: 32

- platform: template
  name: "Exit"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E0B44B
        nbits: 32

- platform: template
  name: "Home"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E09E61
        nbits: 32

- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E0F00F
        nbits: 32

- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E0E01F
        nbits: 32

- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E0D02F
        nbits: 32

- platform: template
  name: "Ch_next"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E048B7
        nbits: 32

- platform: template
  name: "Ch_prev"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E008F7
        nbits: 32
