
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E06798
        nbits: 32

- platform: template
  name: "Settings"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E04BB4
        nbits: 32

- platform: template
  name: "Red/Green/Yellow/Blue"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E0738C
        nbits: 32

- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E006F9
        nbits: 32

- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E08679
        nbits: 32

- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E0A659
        nbits: 32

- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E046B9
        nbits: 32

- platform: template
  name: "Enter"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E046B9
        nbits: 32

- platform: template
  name: "Back"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E01AE5
        nbits: 32

- platform: template
  name: "Home"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E09E61
        nbits: 32

- platform: template
  name: "Play/Pause"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E09D62
        nbits: 32

- platform: template
  name: "Ch_next"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E0E01F
        nbits: 32

- platform: template
  name: "Ch_prev"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E0D02F
        nbits: 32

- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E048B7
        nbits: 32

- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E008F7
        nbits: 32

- platform: template
  name: "Netflix"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E0CF30
        nbits: 32

- platform: template
  name: "Samsung_TV_Plus"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E02DD2
        nbits: 32

- platform: template
  name: "Prime_Video"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E02FD0
        nbits: 32

- platform: template
  name: "Disney_Plus"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xE0E0FB04
        nbits: 32
