
- platform: template
  name: "Power_on"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF20D
        
- platform: template
  name: "Power_off"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE01F
        
- platform: template
  name: "Brightness_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF609
        
- platform: template
  name: "Brightness_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE21D
        
- platform: template
  name: "Red"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE619
        
- platform: template
  name: "Green"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE41B
        
- platform: template
  name: "Blue"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xEE11
        
- platform: template
  name: "White"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xEA15
        
- platform: template
  name: "Flash"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB24D
        
- platform: template
  name: "Strobe"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFF00
        
- platform: template
  name: "Fade"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE51A
        
- platform: template
  name: "Smooth"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF30C
        