
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xDF20
        command: 0xF609
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xDF20
        command: 0xF906
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xDF20
        command: 0xF807
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xDF20
        command: 0xE11E
        
- platform: template
  name: "Bass_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xDF20
        command: 0xF10E
        
- platform: template
  name: "Bass_down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xDF20
        command: 0xE51A
        
- platform: template
  name: "Input"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xDF20
        command: 0xF20D
        
- platform: template
  name: "Treble_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xDF20
        command: 0xFF00
        
- platform: template
  name: "Treble_down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xDF20
        command: 0xFC03
        
- platform: template
  name: "Music"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xDF20
        command: 0xE21D
        
- platform: template
  name: "Cinema"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xDF20
        command: 0xE619
        
- platform: template
  name: "Concert"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xDF20
        command: 0xEA15
        
- platform: template
  name: "Gaming"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xDF20
        command: 0xED12
        
- platform: template
  name: "Bt_pair"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xDF20
        command: 0xFE01
        
- platform: template
  name: "Bt_stop"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xDF20
        command: 0xE01F
        
- platform: template
  name: "Bt_play_pause"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xDF20
        command: 0xE41B
        
- platform: template
  name: "Bt_next"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xDF20
        command: 0xE817
        
- platform: template
  name: "Bt_back"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xDF20
        command: 0xF00F
        
- platform: template
  name: "Reset"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xDF20
        command: 0xEE11
        