
- platform: template
  name: "POWER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFA05
        
- platform: template
  name: "Flame"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB847
        
- platform: template
  name: "Heater"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xEA15
        
- platform: template
  name: "Timer"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE718
        
- platform: template
  name: "C_F"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBA45
        
- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xAD52
        
- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE817
        