
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF42
        command: 0xED12
        
- platform: template
  name: "Source"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF42
        command: 0xE31C
        
- platform: template
  name: "Menu"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF42
        command: 0xF708
        
- platform: template
  name: "Exit"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF42
        command: 0xE817
        
- platform: template
  name: "Enter"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF42
        command: 0xF50A
        
- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF42
        command: 0xFA05
        
- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF42
        command: 0xFF00
        
- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF42
        command: 0xF609
        
- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF42
        command: 0xF807
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF42
        command: 0xE51A
        
- platform: template
  name: "Swap"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF42
        command: 0xFB04
        
- platform: template
  name: "Pip"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF42
        command: 0xF906
        
- platform: template
  name: "Auto"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF42
        command: 0xE11E
        
- platform: template
  name: "Vol_Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF42
        command: 0xE41B
        
- platform: template
  name: "Vol_Dwn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF42
        command: 0xE01F
        