
- platform: template
  name: "Play"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xFF00
        
- platform: template
  name: "Freq_down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xFE01
        
- platform: template
  name: "Freq_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xFD02
        
- platform: template
  name: "Eq"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xFB04
        
- platform: template
  name: "Vol_down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xFA05
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xF906
        
- platform: template
  name: "Prev"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xF609
        
- platform: template
  name: "Next"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xF50A
        
- platform: template
  name: "Song"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xE718
        
- platform: template
  name: "Freq_set"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xE51A
        
- platform: template
  name: "0"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xF708
        
- platform: template
  name: "1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xF30C
        
- platform: template
  name: "2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xF20D
        
- platform: template
  name: "3"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xF10E
        
- platform: template
  name: "4"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xEF10
        
- platform: template
  name: "5"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xEE11
        
- platform: template
  name: "6"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xED12
        
- platform: template
  name: "8"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xEA15
        
- platform: template
  name: "9"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0xE916
        