
- platform: template
  name: "POWER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF20D
        
- platform: template
  name: "Off"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE01F
        
- platform: template
  name: "Brightness +"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF609
        
- platform: template
  name: "Brightness -"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE21D
        
- platform: template
  name: "Red"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE619
        
- platform: template
  name: "Green"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE41B
        
- platform: template
  name: "Blue"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xEE11
        
- platform: template
  name: "White"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xEA15
        
- platform: template
  name: "Dark Orange"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE817
        
- platform: template
  name: "Orange"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBF40
        
- platform: template
  name: "Light Orange"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF50A
        
- platform: template
  name: "Yellow"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE31C
        
- platform: template
  name: "Light Green"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xED12
        
- platform: template
  name: "Turqouise"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB34C
        
- platform: template
  name: "Aqua"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE11E
        
- platform: template
  name: "Teal"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xEB14
        
- platform: template
  name: "Violet"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE916
        
- platform: template
  name: "Purple"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFB04
        
- platform: template
  name: "Pink"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF10E
        
- platform: template
  name: "Magenta"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF00F
        
- platform: template
  name: "Flash"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB24D
        
- platform: template
  name: "Strobe"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFF00
        
- platform: template
  name: "Fade"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE51A
        
- platform: template
  name: "Smooth"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF30C
        