
- platform: template
  name: "POWER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xFF00
        
- platform: template
  name: "High"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xE916
        
- platform: template
  name: "Mid"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xF10E
        
- platform: template
  name: "Low"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xF50A
        
- platform: template
  name: "Swing"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xF906
        
- platform: template
  name: "TEMP+"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xEA15
        
- platform: template
  name: "TEMP-"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xF20D
        
- platform: template
  name: "Cool"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xEB14
        
- platform: template
  name: "Dry"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xF30C
        
- platform: template
  name: "Fan"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xF708
        
- platform: template
  name: "Temp_display"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xFB04
        
- platform: template
  name: "Timer"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xFE01
        