
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8778
        command: 0x33CC
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8778
        command: 0xE11E
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8778
        command: 0xE01F
        
- platform: template
  name: "SUB+"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8778
        command: 0xB34C
        
- platform: template
  name: "SUB-"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8778
        command: 0xB24D
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8778
        command: 0x639C
        
- platform: template
  name: "3D_SURROUND"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8778
        command: 0x36C9
        
- platform: template
  name: "INFO"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8778
        command: 0xB14E
        
- platform: template
  name: "CLEAR_VOICE"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8778
        command: 0xA35C
        
- platform: template
  name: "SURROUND"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8778
        command: 0x4BB4
        
- platform: template
  name: "STEREO"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8778
        command: 0xAF50
        
- platform: template
  name: "HDMI"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8778
        command: 0xB54A
        
- platform: template
  name: "TV"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8778
        command: 0x20DF
        
- platform: template
  name: "ANALOG"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8778
        command: 0x2ED1
        
- platform: template
  name: "BLUETOOTH"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8778
        command: 0xD629
        
- platform: template
  name: "BLUETOOTH_STANDBY"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8778
        command: 0xCB34
        
- platform: template
  name: "DIMMER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8778
        command: 0x45BA
        
- platform: template
  name: "BASE_EXTENSION"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8778
        command: 0x748B
        