
- platform: template
  name: "8 Hour"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0x629D
        
- platform: template
  name: "10 Hour"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0x639C
        
- platform: template
  name: "12 Hour"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0x619E
        
- platform: template
  name: "14 Hour"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0x609F
        
- platform: template
  name: "On"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0x7A85
        
- platform: template
  name: "White"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0x748B
        
- platform: template
  name: "Off"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0x7B84
        
- platform: template
  name: "Red"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0x7689
        
- platform: template
  name: "Green"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0x7788
        
- platform: template
  name: "Play Color Shift"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0x7887
        
- platform: template
  name: "Blue"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0x758A
        
- platform: template
  name: "Stop Color Shift"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0x7986
        
- platform: template
  name: "Red 1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0x728D
        
- platform: template
  name: "Red 2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0x6A95
        
- platform: template
  name: "Red 3"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0x6699
        
- platform: template
  name: "Red 4"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0x6E91
        
- platform: template
  name: "Green 1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0x738C
        
- platform: template
  name: "Green 2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0x6B94
        
- platform: template
  name: "Green 3"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0x6798
        
- platform: template
  name: "Green 4"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0x6F90
        
- platform: template
  name: "Blue 1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0x718E
        
- platform: template
  name: "Blue 2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0x6996
        
- platform: template
  name: "Blue 3"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0x659A
        
- platform: template
  name: "Blue 4"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0x6D92
        
- platform: template
  name: "Level 4"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0x708F
        
- platform: template
  name: "Level 3"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0x6897
        
- platform: template
  name: "Level 2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0x649B
        
- platform: template
  name: "Level 1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0x6C93
        