
- platform: template
  name: "POWER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8801
        command: 0x8F70
        
- platform: template
  name: "Playlists"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8801
        command: 0x8778
        
- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8801
        command: 0x8D72
        
- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8801
        command: 0x8877
        
- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8801
        command: 0x8B74
        
- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8801
        command: 0x8976
        
- platform: template
  name: "OK"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8801
        command: 0x8A75
        
- platform: template
  name: "Back"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8801
        command: 0x8E71
        
- platform: template
  name: "Settings"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8801
        command: 0x857A
        
- platform: template
  name: "Vol +"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8801
        command: 0x9768
        
- platform: template
  name: "Vol -"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8801
        command: 0x9669
        