
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xA05F
        
- platform: template
  name: "Eject"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB14E
        
- platform: template
  name: "Menu"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE31C
        
- platform: template
  name: "Info"
  on_press:
    - remote_transmitter.transmit_raw:
        carrier_frequency: 38kHz
        code: [8985, -4499, 592, -531, 593, -531, 593, -532, 592, -531, 593, -531, 593, -532, 592, -533, 591, -536, 566, -1663, 593, -1640, 594, -1642, 592, -1641, 593, -1643, 591, -1641, 593, -1642, 592, -1643, 591, -1550, 684, -1643, 591, -1642, 592, -532, 592, -1643, 591, -532, 592, -532, 592, -532, 592, -534, 590, -532, 592, -532, 592, -1642, 592, -534, 590, -1644, 590, -1625, 609, -1643, 591, -40176, 9015, -2241, 564]
    
- platform: template
  name: "Ok"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xAA55
        
- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xA659
        
- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xAE51
        
- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xA956
        
- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xEB14
        
- platform: template
  name: "Fast_fo"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBF40
        
- platform: template
  name: "Fast_ba"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xA25D
        
- platform: template
  name: "Pause"
  on_press:
    - remote_transmitter.transmit_raw:
        carrier_frequency: 38kHz
        code: [8983, -4501, 564, -559, 565, -559, 565, -558, 566, -559, 565, -558, 566, -442, 682, -566, 558, -560, 564, -1669, 565, -1669, 565, -1669, 565, -1670, 564, -1669, 565, -1668, 566, -1599, 635, -1670, 564, -560, 564, -560, 564, -560, 564, -1669, 565, -1669, 565, -559, 565, -1670, 564, -559, 565, -1668, 566, -1669, 565, -1669, 565, -559, 565, -558, 566, -1670, 564, -560, 564, -1669, 565, -40232, 8985, -2239, 566]
    
- platform: template
  name: "Play"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xA45B
        
- platform: template
  name: "Stop"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE41B
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB54A
        
- platform: template
  name: "Subtitle"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFD02
        
- platform: template
  name: "Audio"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBC43
        
- platform: template
  name: "Popup"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xEF10
        