
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x6798
        
- platform: template
  name: "Mode"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x6B94
        
- platform: template
  name: "Timer"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x6F90
        
- platform: template
  name: "Temp_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x738C
        
- platform: template
  name: "Temp_down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x7788
        