
- platform: template
  name: "Home"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xC2EA
        command: 0xFC03
        
- platform: template
  name: "Ok"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xC2EA
        command: 0xD52A
        
- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xC2EA
        command: 0xE11E
        
- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xC2EA
        command: 0xD22D
        
- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xC2EA
        command: 0xE619
        
- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xC2EA
        command: 0xCC33
        
- platform: template
  name: "Rewind"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xC2EA
        command: 0xCB34
        
- platform: template
  name: "Play"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xC2EA
        command: 0xB34C
        
- platform: template
  name: "FFWD"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xC2EA
        command: 0xAA55
        
- platform: template
  name: "Back"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xC2EA
        command: 0x9966
        
- platform: template
  name: "Replay"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xC2EA
        command: 0x8778
        
- platform: template
  name: "Options"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xC2EA
        command: 0x9E61
        