
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x707030CF
        nbits: 32

- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x7070B04F
        nbits: 32

- platform: template
  name: "Menu"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x70708877
        nbits: 32

- platform: template
  name: "Source"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x7070F00F
        nbits: 32

- platform: template
  name: "Ok"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x7070629D
        nbits: 32

- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x707042BD
        nbits: 32

- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x7070C23D
        nbits: 32

- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x707022DD
        nbits: 32

- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x7070A25D
        nbits: 32

- platform: template
  name: "Browser"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x7070CA35
        nbits: 32

- platform: template
  name: "Exit"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x7070AD52
        nbits: 32

- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x707028D7
        nbits: 32

- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x7070A857
        nbits: 32

- platform: template
  name: "Ch_next"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x707048B7
        nbits: 32

- platform: template
  name: "Ch_prev"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x7070C837
        nbits: 32

- platform: template
  name: "Home"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x70701EE1
        nbits: 32

- platform: template
  name: "1"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x7070807F
        nbits: 32

- platform: template
  name: "2"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x707040BF
        nbits: 32

- platform: template
  name: "3"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x7070C03F
        nbits: 32

- platform: template
  name: "4"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x707020DF
        nbits: 32

- platform: template
  name: "5"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x7070A05F
        nbits: 32

- platform: template
  name: "6"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x7070609F
        nbits: 32

- platform: template
  name: "7"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x7070E01F
        nbits: 32

- platform: template
  name: "8"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x707010EF
        nbits: 32

- platform: template
  name: "9"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x7070906F
        nbits: 32

- platform: template
  name: "0"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x707000FF
        nbits: 32

- platform: template
  name: "Back"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x7070DD22
        nbits: 32
