
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF40
        command: 0xED12
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF40
        command: 0xE51A
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF40
        command: 0xE11E
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF40
        command: 0xEF10
        
- platform: template
  name: "Info"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF40
        command: 0xE31C
        
- platform: template
  name: "Input"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF40
        command: 0xF00F
        