
- platform: template
  name: "On"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF807
        
- platform: template
  name: "Off"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF906
        
- platform: template
  name: "Red"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF609
        
- platform: template
  name: "White"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF40B
        
- platform: template
  name: "Green"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF708
        
- platform: template
  name: "Blue"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF50A
        
- platform: template
  name: "Flash"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF00F
        
- platform: template
  name: "Strobe"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE817
        