
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0xA9A
        nbits: 12

- platform: template
  name: "Eject"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x69A
        nbits: 12

- platform: template
  name: "Menu"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0xB3A
        nbits: 12

- platform: template
  name: "Ok"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x59A
        nbits: 12

- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x385D
        nbits: 15

- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x785D
        nbits: 15

- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x45D
        nbits: 15

- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x445D
        nbits: 15

- platform: template
  name: "Fast_fo"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x445D
        nbits: 15

- platform: template
  name: "Fast_ba"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x45D
        nbits: 15

- platform: template
  name: "Pause"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x385D
        nbits: 15

- platform: template
  name: "Play"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x59A
        nbits: 12

- platform: template
  name: "Stop"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x785D
        nbits: 15

- platform: template
  name: "Enter"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0xD1A
        nbits: 12
