
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0x7E81
        
- platform: template
  name: "Menu"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0x7C83
        
- platform: template
  name: "Back"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xD827
        
- platform: template
  name: "Ok"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xEC13
        
- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xC738
        
- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xBF40
        
- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xC837
        
- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xC639
        
- platform: template
  name: "Input Source"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0x8C73
        
- platform: template
  name: "Post Process"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0x7689
        
- platform: template
  name: "Scale/Crop"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0x7887
        
- platform: template
  name: "Horz Sampl"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xB748
        