
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBD02
        command: 0xAC53
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBD02
        command: 0x52AD
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBD02
        command: 0xD926
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBD02
        command: 0xD728
        
- platform: template
  name: "BT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBD02
        command: 0xE41B
        
- platform: template
  name: "BT_Pair"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBD02
        command: 0xF708
        
- platform: template
  name: "AUX"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBD02
        command: 0xB24D
        
- platform: template
  name: "USB"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBD02
        command: 0xDF20
        
- platform: template
  name: "Play"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBD02
        command: 0xF20D
        
- platform: template
  name: "Next"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBD02
        command: 0xD827
        
- platform: template
  name: "Prev"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBD02
        command: 0xDA25
        