
- platform: template
  name: "POWER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x6F90
        
- platform: template
  name: "Hdmi_1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x8C73
        
- platform: template
  name: "Hdmi_2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x8877
        
- platform: template
  name: "Lan"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x8B74
        
- platform: template
  name: "Video"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x8F70
        
- platform: template
  name: "Pc"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x629D
        
- platform: template
  name: "Play"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0xA15E
        
- platform: template
  name: "Pause"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0xA45B
        
- platform: template
  name: "Stop"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0xA659
        
- platform: template
  name: "VOL-"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x6699
        
- platform: template
  name: "VOL+"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x6798
        
- platform: template
  name: "Menu"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x659A
        
- platform: template
  name: "Enter"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x7A85
        
- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x4FB0
        
- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x4DB2
        
- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x4CB3
        
- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x4EB1
        
- platform: template
  name: "Home"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x6A95
        