
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x6F90
        
- platform: template
  name: "Source"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x738C
        
- platform: template
  name: "Help"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x6A95
        
- platform: template
  name: "Menu"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x659A
        
- platform: template
  name: "Enter"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x7A85
        
- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x4FB0
        
- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x4DB2
        
- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x4CB3
        
- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x4EB1
        
- platform: template
  name: "Esc"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x7B84
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x4EB1
        
- platform: template
  name: "Vol_down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x4CB3
        
- platform: template
  name: "ColorMode"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x708F
        
- platform: template
  name: "Aspect"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x758A
        
- platform: template
  name: "Freeze"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x6D92
        
- platform: template
  name: "A_V_Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x6C93
        
- platform: template
  name: "E_Zoom_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x7788
        
- platform: template
  name: "E_Zoom_down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x5583
        command: 0x7689
        