
- platform: template
  name: "On"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFE01
        
- platform: template
  name: "Off"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFE01
        
- platform: template
  name: "Night"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFA05
        
- platform: template
  name: "Ct_plus"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFD02
        
- platform: template
  name: "Ct_minus"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFC03
        
- platform: template
  name: "Bulb"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0x00FF
        
- platform: template
  name: "Auxiliary"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xE51A
        