
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_pronto:
        d

- platform: template
  name: "Volume_p"
  on_press:
    - remote_transmitter.transmit_pronto:
        d

- platform: template
  name: "Volume_m"
  on_press:
    - remote_transmitter.transmit_pronto:
        d
