
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFF00
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFC03
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF906
        
- platform: template
  name: "Bass+"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFE01
        
- platform: template
  name: "Bass-"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFB04
        
- platform: template
  name: "Treble+"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFD02
        
- platform: template
  name: "Treble-"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFA05
        
- platform: template
  name: "IPod"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF807
        
- platform: template
  name: "CD"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF708
        
- platform: template
  name: "FM"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF609
        
- platform: template
  name: "Air"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF10E
        
- platform: template
  name: "LineIn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xEF10
        
- platform: template
  name: "Play_Pause"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF50A
        
- platform: template
  name: "Next"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF30C
        
- platform: template
  name: "Prev"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF40B
        
- platform: template
  name: "Stop"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF20D
        
- platform: template
  name: "Eject"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF00F
        
- platform: template
  name: "P"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xEE11
        
- platform: template
  name: "R"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xED12
        
- platform: template
  name: "E"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xEC13
        
- platform: template
  name: "S"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xEB14
        
- platform: template
  name: "E"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xEA15
        
- platform: template
  name: "T"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE916
        