
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0xB946
        
- platform: template
  name: "Home"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0x609F
        
- platform: template
  name: "Menu"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0xBA45
        
- platform: template
  name: "Back"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0xF20D
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0xF30C
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0xE619
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0xB34C
        
- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0xB748
        
- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0xB24D
        
- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0xB14E
        
- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0xB649
        
- platform: template
  name: "Select"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0xB54A
        
- platform: template
  name: "Rewind"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0xE916
        
- platform: template
  name: "Play_pause"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0xA45B
        
- platform: template
  name: "Fast_forward"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0xE817
        
- platform: template
  name: "Guide"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0xEB14
        
- platform: template
  name: "Ch_next"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0xF00F
        
- platform: template
  name: "Ch_prev"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0xA55A
        
- platform: template
  name: "Recent_apps"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0x4EB1
        
- platform: template
  name: "Disney_plus"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0x5DA2
        
- platform: template
  name: "Freevie"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0x2DD2
        
- platform: template
  name: "Netflix"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0xA05F
        
- platform: template
  name: "Prime_video"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0x5EA1
        
- platform: template
  name: "Hulu"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0x5AA5
        
- platform: template
  name: "Settings"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0x6996
        
- platform: template
  name: "Magnifier"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0x37C8
        
- platform: template
  name: "Voice_view"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0x3FC0
        
- platform: template
  name: "Bluetooth"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0x59A6
        
- platform: template
  name: "Resolution"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0x31CE
        
- platform: template
  name: "Networking"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0x30CF
        
- platform: template
  name: "Reboot"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0x35CA
        
- platform: template
  name: "Factory_reset"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0x36C9
        
- platform: template
  name: "Alexa"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7D02
        command: 0x5FA0
        