
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_rc6:
        address: 0x00
        command: 0x10

- platform: template
  name: "Vol_down"
  on_press:
    - remote_transmitter.transmit_rc6:
        address: 0x00
        command: 0x11

- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_rc6:
        address: 0x00
        command: 0x0D
