
- platform: template
  name: "POWER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xE21D
        
- platform: template
  name: "MUTE"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xF20D
        
- platform: template
  name: "Presets"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xFB04
        
- platform: template
  name: "Play_pause"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xE718
        
- platform: template
  name: "VOL+"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xF10E
        
- platform: template
  name: "VOL-"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xF30C
        
- platform: template
  name: "Back"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xEB14
        
- platform: template
  name: "Fwd"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xE916
        
- platform: template
  name: "Equalizer"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xF708
        
- platform: template
  name: "Snooze"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xFA05
        
- platform: template
  name: "Sleep"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xF50A
        
- platform: template
  name: "Mode"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xF906
        
- platform: template
  name: "Minus"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xEF10
        
- platform: template
  name: "Plus"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xED12
        