
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xE11E
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFE01
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFC03
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF906
        
- platform: template
  name: "Bluetooth"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF20D
        
- platform: template
  name: "Analog"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF10E
        
- platform: template
  name: "Digital"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF30C
        
- platform: template
  name: "LED"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xE01F
        
- platform: template
  name: "Surround"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFB04
        
- platform: template
  name: "Dialog"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xD42B
        