
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x0C
    
- platform: template
  name: "Vol_Up"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x10
    
- platform: template
  name: "Vol_Down"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x11
    
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x0D
    
- platform: template
  name: "Ch_Up"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x20
    
- platform: template
  name: "Ch_Down"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x21
    
- platform: template
  name: "Menu"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x0B
    
- platform: template
  name: "AV"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x38
    
- platform: template
  name: "TV"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x3F
    
- platform: template
  name: "Text"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x3C
    
- platform: template
  name: "1"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x01
    
- platform: template
  name: "2"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x02
    
- platform: template
  name: "3"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x03
    
- platform: template
  name: "4"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x04
    
- platform: template
  name: "5"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x05
    
- platform: template
  name: "6"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x06
    
- platform: template
  name: "7"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x07
    
- platform: template
  name: "8"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x08
    
- platform: template
  name: "9"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x09
    
- platform: template
  name: "0"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x00
    
- platform: template
  name: "Select"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x3B
    
- platform: template
  name: "Info"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x0F
    
- platform: template
  name: "Timer"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x26
    
- platform: template
  name: "SYST"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x3D
    
- platform: template
  name: "Store"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x27
    
- platform: template
  name: "P100"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x35
    
- platform: template
  name: "RED"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x37
    
- platform: template
  name: "GREEN"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x36
    
- platform: template
  name: "YELLOW"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x32
    
- platform: template
  name: "BLUE"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x34
    
- platform: template
  name: "Clock"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x2A
    
- platform: template
  name: "Update"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x2D
    
- platform: template
  name: "MIX"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x2E
    
- platform: template
  name: "Double"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x2B
    
- platform: template
  name: "Reval"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x2C
    
- platform: template
  name: "Hold"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x29
    
- platform: template
  name: "Stereo"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x2F
    
- platform: template
  name: "Mono AB"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x23
    
- platform: template
  name: "PS"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x24
    