
- platform: template
  name: "1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x6B86
        command: 0xFE01
        
- platform: template
  name: "2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x6B86
        command: 0xFD02
        
- platform: template
  name: "3"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x6B86
        command: 0xFC03
        
- platform: template
  name: "4"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x6B86
        command: 0xFB04
        
- platform: template
  name: "POWER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x6B86
        command: 0xED12
        