
- platform: template
  name: "On"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xED12
        
- platform: template
  name: "Off"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xE11E
        
- platform: template
  name: "Play_pause"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF20D
        
- platform: template
  name: "Next"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xE619
        
- platform: template
  name: "Prev"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFF00
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF906
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xE01F
        
- platform: template
  name: "Brightness_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFB04
        
- platform: template
  name: "Brightness_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF50A
        