
- platform: template
  name: "POWER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE31C
        
- platform: template
  name: "Oscillation"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE718
        
- platform: template
  name: "Strength"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE619
        
- platform: template
  name: "Silent"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF609
        
- platform: template
  name: "Timer"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBF40
        
- platform: template
  name: "Moustic"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF807
        