
- platform: template
  name: "VCR_STOP_[]"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0090
        command: 0xFF00
        
- platform: template
  name: "VCR_<<"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0090
        command: 0xFD02
        
- platform: template
  name: "VCR_>>"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0090
        command: 0xFC03
        
- platform: template
  name: "VCR_PAUSE"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0090
        command: 0xF906
        
- platform: template
  name: "VCR_REC"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0090
        command: 0xF708
        
- platform: template
  name: "VCR_PLAY_>"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0090
        command: 0xF50A
        
- platform: template
  name: "VCR_1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0090
        command: 0xEF10
        
- platform: template
  name: "VCR_2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0090
        command: 0xEE11
        
- platform: template
  name: "VCR_3"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0090
        command: 0xED12
        
- platform: template
  name: "VCR_4"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0090
        command: 0xEC13
        
- platform: template
  name: "VCR_5"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0090
        command: 0xEB14
        
- platform: template
  name: "VCR_6"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0090
        command: 0xEA15
        
- platform: template
  name: "VCR_7"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0090
        command: 0xE916
        
- platform: template
  name: "VCR_8"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0090
        command: 0xE817
        
- platform: template
  name: "VCR_9"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0090
        command: 0xE718
        
- platform: template
  name: "VCR_0"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0090
        command: 0xE619
        
- platform: template
  name: "VCR_CH_^"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0090
        command: 0xCB34
        
- platform: template
  name: "VCR_CH_V"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0090
        command: 0xCA35
        
- platform: template
  name: "TV/VCR"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0090
        command: 0xC936
        
- platform: template
  name: "VCR_POWER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0090
        command: 0xC23D
        