
- platform: template
  name: "Power_on"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB946
        
- platform: template
  name: "Power_off"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xEA15
        
- platform: template
  name: "Flicker_on"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB54A
        
- platform: template
  name: "Flicker_off"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE51A
        
- platform: template
  name: "Brightness_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE619
        
- platform: template
  name: "Brightness_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xC738
        
- platform: template
  name: "Timer_4_hours"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE916
        
- platform: template
  name: "Timer_6_hours"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFA05
        
- platform: template
  name: "Timer_8_hours"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xEE11
        
- platform: template
  name: "Timer_10_hours"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE718
        