
- platform: template
  name: "^"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0004
        command: 0xFF00
        
- platform: template
  name: "^_(CHANNEL)"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0004
        command: 0xFF00
        
- platform: template
  name: "CHANNEL_^"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0004
        command: 0xFF00
        
- platform: template
  name: "CH^"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0004
        command: 0xFF00
        
- platform: template
  name: "V"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0004
        command: 0xFE01
        
- platform: template
  name: "V_(CHANNEL)"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0004
        command: 0xFE01
        
- platform: template
  name: "CHANNEL_V"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0004
        command: 0xFE01
        
- platform: template
  name: "CHV"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0004
        command: 0xFE01
        
- platform: template
  name: "VOL_^"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0004
        command: 0xFD02
        
- platform: template
  name: "VOL^"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0004
        command: 0xFD02
        
- platform: template
  name: "VOL_V"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0004
        command: 0xFC03
        
- platform: template
  name: "VOLV"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0004
        command: 0xFC03
        
- platform: template
  name: "POWER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0004
        command: 0xF708
        
- platform: template
  name: "MUTE"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0004
        command: 0xF609
        
- platform: template
  name: "ANT_A/B"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0004
        command: 0xF50A
        
- platform: template
  name: "OFF_TIMER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0004
        command: 0xF10E
        
- platform: template
  name: "0"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0004
        command: 0xEF10
        
- platform: template
  name: "1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0004
        command: 0xEE11
        
- platform: template
  name: "2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0004
        command: 0xED12
        
- platform: template
  name: "3"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0004
        command: 0xEC13
        
- platform: template
  name: "4"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0004
        command: 0xEB14
        
- platform: template
  name: "5"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0004
        command: 0xEA15
        
- platform: template
  name: "6"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0004
        command: 0xE916
        
- platform: template
  name: "7"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0004
        command: 0xE817
        
- platform: template
  name: "8"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0004
        command: 0xE718
        
- platform: template
  name: "9"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0004
        command: 0xE619
        
- platform: template
  name: "QUICK_VIEW"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0004
        command: 0xE51A
        
- platform: template
  name: "OFF_TIMER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0004
        command: 0xE41B
        