
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7A83
        command: 0xF708
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7A83
        command: 0xF609
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7A83
        command: 0xFD02
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7A83
        command: 0xFC03
        
- platform: template
  name: "Ch_prev"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7A83
        command: 0xFE01
        
- platform: template
  name: "Ch_next"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7A83
        command: 0xFF00
        
- platform: template
  name: "Display"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7A83
        command: 0xF807
        
- platform: template
  name: "Status/Exit"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7A83
        command: 0xFB04
        
- platform: template
  name: "-"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7A83
        command: 0xFA05
        
- platform: template
  name: "+"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7A83
        command: 0xF906
        
- platform: template
  name: "Alt_ch"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7A83
        command: 0xE51A
        
- platform: template
  name: "Timer"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7A83
        command: 0xE31C
        
- platform: template
  name: "Num0"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7A83
        command: 0xEF10
        
- platform: template
  name: "Num1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7A83
        command: 0xEE11
        
- platform: template
  name: "Num2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7A83
        command: 0xED12
        
- platform: template
  name: "Num3"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7A83
        command: 0xEC13
        
- platform: template
  name: "Num4"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7A83
        command: 0xEB14
        
- platform: template
  name: "Num5"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7A83
        command: 0xEA15
        
- platform: template
  name: "Num6"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7A83
        command: 0xE916
        
- platform: template
  name: "Num7"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7A83
        command: 0xE817
        
- platform: template
  name: "Num8"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7A83
        command: 0xE718
        
- platform: template
  name: "Num9"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7A83
        command: 0xE619
        
- platform: template
  name: "Something AFx"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7A83
        command: 0xF00F
        