
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x22DD
        
- platform: template
  name: "Fan_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x3FC0
        
- platform: template
  name: "Fan_down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB946
        
- platform: template
  name: "Info"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xCC33
        
- platform: template
  name: "Auto"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFC03
        
- platform: template
  name: "Brightness"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x33CC
        
- platform: template
  name: "Time_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF30C
        
- platform: template
  name: "Time_down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x9B64
        