
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x14
        command: 0x0C
    
- platform: template
  name: "Tray"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x14
        command: 0x2D
    
- platform: template
  name: "Door"
  on_press:
    - remote_transmitter.transmit_raw:
        carrier_frequency: 38kHz
        code: [891, -882, 1782, -1770, 1780, -1770, 1780, -885, 889, -5324, 1778, -1771, 891, -884, 1780, -1772, 1778, -884, 890, -883, 892, -884, 891, -886, 889, -885, 890]
    
- platform: template
  name: "Repeat"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x14
        command: 0x1D
    
- platform: template
  name: "Prog"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x14
        command: 0x24
    
- platform: template
  name: "Random"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x14
        command: 0x1C
    
- platform: template
  name: "1"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x14
        command: 0x01
    
- platform: template
  name: "2"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x14
        command: 0x02
    
- platform: template
  name: "3"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x14
        command: 0x03
    
- platform: template
  name: "4"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x14
        command: 0x04
    
- platform: template
  name: "5"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x14
        command: 0x05
    
- platform: template
  name: "6"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x14
        command: 0x06
    
- platform: template
  name: "7"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x14
        command: 0x07
    
- platform: template
  name: "8"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x14
        command: 0x08
    
- platform: template
  name: "9"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x14
        command: 0x09
    
- platform: template
  name: "0"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x14
        command: 0x00
    
- platform: template
  name: "Display"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x14
        command: 0x0F
    
- platform: template
  name: "Scroll"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x14
        command: 0x0B
    
- platform: template
  name: "Cdr"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x1A
        command: 0x3F
    
- platform: template
  name: "Cd"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x14
        command: 0x3F
    
- platform: template
  name: "Menu"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x14
        command: 0x12

- platform: template
  name: "Prev"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x14
        command: 0x21
    
- platform: template
  name: "Next"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x14
        command: 0x20
    
- platform: template
  name: "Cancel"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x14
        command: 0x31
    
- platform: template
  name: "Rev"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x14
        command: 0x32
    
- platform: template
  name: "Ff"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x14
        command: 0x34
    
- platform: template
  name: "Pause"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x14
        command: 0x30
    
- platform: template
  name: "Stop"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x14
        command: 0x36
    
- platform: template
  name: "Play"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x14
        command: 0x35
    