
- platform: template
  name: "On"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBA45
        
- platform: template
  name: "Off"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB847
        
- platform: template
  name: "Dim"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF708
        
- platform: template
  name: "Brighten"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xA55A
        
- platform: template
  name: "Mode_1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBB44
        
- platform: template
  name: "Mode_2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBC43
        
- platform: template
  name: "Mode_3"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF807
        
- platform: template
  name: "Mode_4"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF609
        
- platform: template
  name: "Mode_5"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE916
        
- platform: template
  name: "Mode_6"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF20D
        
- platform: template
  name: "Mode_7"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF30C
        
- platform: template
  name: "Mode_8"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xA15E
        