
- platform: template
  name: "POWER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x3000
        command: 0xFD02
        
- platform: template
  name: "PLAYPAUSE"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x3000
        command: 0xFC03
        
- platform: template
  name: "CYCLEWINDOWS"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x3000
        command: 0xFB04
        
- platform: template
  name: "PAGEUP"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x3000
        command: 0xFA05
        
- platform: template
  name: "PAGEDOWN"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x3000
        command: 0xF906
        
- platform: template
  name: "blank"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x3000
        command: 0xF807
        
- platform: template
  name: "auto"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x3000
        command: 0xF708
        
- platform: template
  name: "keystone-larger"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x3000
        command: 0xF609
        
- platform: template
  name: "keystone-smaller"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x3000
        command: 0xF50A
        
- platform: template
  name: "UP"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x3000
        command: 0xF40B
        
- platform: template
  name: "DOWN"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x3000
        command: 0xF30C
        
- platform: template
  name: "LEFT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x3000
        command: 0xF20D
        
- platform: template
  name: "RIGHT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x3000
        command: 0xF10E
        
- platform: template
  name: "MENU"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x3000
        command: 0xF00F
        
- platform: template
  name: "preset"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x3000
        command: 0xEF10
        
- platform: template
  name: "keystone-auto"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x3000
        command: 0xEE11
        