
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xB4B40CF3
        nbits: 32

- platform: template
  name: "1"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xB4B4DC23
        nbits: 32

- platform: template
  name: "2"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xB4B43CC3
        nbits: 32

- platform: template
  name: "3"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xB4B4BC43
        nbits: 32

- platform: template
  name: "4"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xB4B47C83
        nbits: 32

- platform: template
  name: "5"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xB4B4FC03
        nbits: 32

- platform: template
  name: "6"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xB4B402FD
        nbits: 32

- platform: template
  name: "7"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xB4B4827D
        nbits: 32

- platform: template
  name: "8"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xB4B442BD
        nbits: 32

- platform: template
  name: "9"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xB4B4C23D
        nbits: 32

- platform: template
  name: "0"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0xB4B422DD
        nbits: 32
