
- platform: template
  name: "Green_call"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0x8778
        
- platform: template
  name: "Red_call"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0x07F8
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0x13EC
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0x53AC
        
- platform: template
  name: "Vol_down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0x936C
        
- platform: template
  name: "Zoom_in"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0x5DA2
        
- platform: template
  name: "Zoom_out"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0x1DE2
        
- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0x4BB4
        
- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0x43BC
        
- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0x03FC
        
- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFD02
        command: 0x0BF4
        