
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x5499
        nbits: 15

- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x1499
        nbits: 15

- platform: template
  name: "Input"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x299
        nbits: 15

- platform: template
  name: "Play"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0xA99
        nbits: 15

- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x2499
        nbits: 15

- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x6499
        nbits: 15

- platform: template
  name: "Bass"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x4699
        nbits: 15

- platform: template
  name: "Next"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x4A99
        nbits: 15

- platform: template
  name: "Prev"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x2A99
        nbits: 15
