
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF807
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xEB14
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF708
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFF00
        
- platform: template
  name: "Bass_Level"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE41B
        
- platform: template
  name: "Bass_Mgmt_On"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFC03
        
- platform: template
  name: "Bass_Mgmt_Xover"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF40B
        
- platform: template
  name: "Brightness"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE01F
        
- platform: template
  name: "Dim"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFF00
        
- platform: template
  name: "EQ_HF"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE619
        
- platform: template
  name: "EQ_LF"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE31C
        
- platform: template
  name: "EQ_LFE_Filter"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE21D
        
- platform: template
  name: "EQ_On"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF609
        
- platform: template
  name: "EQ_Preset"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE718
        
- platform: template
  name: "Input"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFB04
        
- platform: template
  name: "RMC"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE817
        
- platform: template
  name: "Solo_Center"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE916
        
- platform: template
  name: "SoloCntrSurr"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF50A
        
- platform: template
  name: "Solo_LRXtra"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFE01
        
- platform: template
  name: "Solo_Left"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xF906
        
- platform: template
  name: "SoloLeftSurr"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFD02
        
- platform: template
  name: "Solo_Right"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE11E
        
- platform: template
  name: "SoloRightSurr"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE51A
        
- platform: template
  name: "Solo_Sub1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFA05
        
- platform: template
  name: "Solo_Sub2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xEA15
        