
- platform: template
  name: "ON / OFF"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xE31C
        
- platform: template
  name: "White"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xE21D
        
- platform: template
  name: "Rainbow"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xE11E
        
- platform: template
  name: "Pattern 1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xFA05
        
- platform: template
  name: "Pattern 2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xF906
        
- platform: template
  name: "Pattern 3"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xE718
        
- platform: template
  name: "Pattern 4"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xE619
        
- platform: template
  name: "Pattern 5"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xE51A
        
- platform: template
  name: "Red(1)"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xF708
        
- platform: template
  name: "Green(2)"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xF609
        
- platform: template
  name: "Blue(3)"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xF50A
        
- platform: template
  name: "Yellow(1)"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xEB14
        
- platform: template
  name: "Light Blue(2)"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xEA15
        
- platform: template
  name: "Purple(3)"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xE916
        
- platform: template
  name: "*"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xFF00
        
- platform: template
  name: "**"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xFE01
        
- platform: template
  name: "***"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xFD02
        
- platform: template
  name: "****"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xFC03
        
- platform: template
  name: "*****"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xFB04
        