
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xED12
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF20D
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF708
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xE11E
        
- platform: template
  name: "Bluetooth"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFE01
        
- platform: template
  name: "Optical"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFC03
        
- platform: template
  name: "Aux"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFD02
        
- platform: template
  name: "Play/Pause"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xE41B
        
- platform: template
  name: "Back"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF50A
        
- platform: template
  name: "Forward"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xE01F
        
- platform: template
  name: "Music"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xE51A
        
- platform: template
  name: "Game"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xE21D
        
- platform: template
  name: "Cinema"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xE31C
        