
- platform: template
  name: "On"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xFF00
        
- platform: template
  name: "Speed"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xF906
        
- platform: template
  name: "Plus"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xFE01
        
- platform: template
  name: "Minus"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xFD02
        
- platform: template
  name: "Steralise"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xFA05
        
- platform: template
  name: "Anion"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xFB04
        
- platform: template
  name: "Sleep"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xF807
        
- platform: template
  name: "Timer"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xFC03
        