
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x34347887
        nbits: 32

- platform: template
  name: "Eject"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x343459A6
        nbits: 32

- platform: template
  name: "Menu"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x343425DA
        nbits: 32

- platform: template
  name: "Back"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x343445BA
        nbits: 32

- platform: template
  name: "Ok"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x343455AA
        nbits: 32

- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x3434E51A
        nbits: 32

- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x3434659A
        nbits: 32

- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x343415EA
        nbits: 32

- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x3434956A
        nbits: 32

- platform: template
  name: "Fast_fo"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x34344AB5
        nbits: 32

- platform: template
  name: "Fast_ba"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x3434CA35
        nbits: 32

- platform: template
  name: "Pause"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x3434F20D
        nbits: 32

- platform: template
  name: "Play"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x343420DF
        nbits: 32

- platform: template
  name: "Stop"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x3434A05F
        nbits: 32

- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x3434F807
        nbits: 32

- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x3434E817
        nbits: 32

- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x34346897
        nbits: 32

- platform: template
  name: "Subtitle"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x3434D52A
        nbits: 32

- platform: template
  name: "Audio"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x34346C93
        nbits: 32

- platform: template
  name: "Home"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x3434A55A
        nbits: 32

- platform: template
  name: "Record"
  on_press:
    - remote_transmitter.transmit_samsung:
        data: 0x3434C13E
        nbits: 32
