
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xFE01
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xFF00
        
- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xF30C
        
- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xF609
        
- platform: template
  name: "Line1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xF50A
        
- platform: template
  name: "Line2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xEA15
        
- platform: template
  name: "Opt"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xF20D
        
- platform: template
  name: "Cox"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xE916
        
- platform: template
  name: "Bluetooth"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xF10E
        
- platform: template
  name: "Play_Pause"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xEB14
        
- platform: template
  name: "Back"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xF906
        
- platform: template
  name: "Forward"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xF708
        