
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xFE01
        
- platform: template
  name: "On/Off"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xFF00
        
- platform: template
  name: "-"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xF30C
        
- platform: template
  name: "+"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xF609
        
- platform: template
  name: "Line1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xF50A
        
- platform: template
  name: "Line2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xEA15
        
- platform: template
  name: "Optical"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xF20D
        
- platform: template
  name: "COAX"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xE916
        
- platform: template
  name: "Bluetooth"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xE710
        command: 0xF10E
        