
- platform: template
  name: "0"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xFF00
        
- platform: template
  name: "1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xFE01
        
- platform: template
  name: "2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xFD02
        
- platform: template
  name: "3"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xFC03
        
- platform: template
  name: "4"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xFB04
        
- platform: template
  name: "5"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xFA05
        
- platform: template
  name: "6"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xF906
        
- platform: template
  name: "7"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xF807
        
- platform: template
  name: "8"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xF708
        
- platform: template
  name: "9"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xF609
        
- platform: template
  name: "BRIGHTNESS"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xF50A
        
- platform: template
  name: "IN2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xF20D
        
- platform: template
  name: "CONTRAST"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xF10E
        
- platform: template
  name: "CURSOR_LEFT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xF00F
        
- platform: template
  name: "MENU"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xEF10
        
- platform: template
  name: "MUTE"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xEF10
        
- platform: template
  name: "IN3"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xEE11
        
- platform: template
  name: "CURSOR_UP"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xED12
        
- platform: template
  name: "POWER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xEC13
        
- platform: template
  name: "EXIT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xEB14
        
- platform: template
  name: "CURSOR_RIGHT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xEA15
        
- platform: template
  name: "ASPECT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xE916
        
- platform: template
  name: "RESOLUTION"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xE817
        
- platform: template
  name: "PASS"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xE718
        
- platform: template
  name: "R1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xE718
        
- platform: template
  name: "IN4"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xE619
        
- platform: template
  name: "IN1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xE51A
        
- platform: template
  name: "RSRV"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xE41B
        
- platform: template
  name: "CURSOR_DOWN"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xE21D
        
- platform: template
  name: "OFF"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xE11E
        
- platform: template
  name: "INPUT_SELECT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0084
        command: 0xE01F
        