
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF00
        command: 0xF20D
        
- platform: template
  name: "Source"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF00
        command: 0xED12
        
- platform: template
  name: "Menu"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF00
        command: 0xEB14
        
- platform: template
  name: "Exit"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF00
        command: 0xB748
        
- platform: template
  name: "Ok"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF00
        command: 0xEA15
        
- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF00
        command: 0xE916
        
- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF00
        command: 0xE817
        
- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF00
        command: 0xE619
        
- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF00
        command: 0xE718
        
- platform: template
  name: "Fast_fo"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF00
        command: 0xA659
        
- platform: template
  name: "Fast_ba"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF00
        command: 0xA758
        
- platform: template
  name: "Pause"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF00
        command: 0x56A9
        
- platform: template
  name: "Play"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF00
        command: 0x57A8
        
- platform: template
  name: "Stop"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF00
        command: 0xA55A
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF00
        command: 0xF10E
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF00
        command: 0xBB44
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF00
        command: 0xBC43
        
- platform: template
  name: "Ch_next"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF00
        command: 0xB54A
        
- platform: template
  name: "Ch_prev"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF00
        command: 0xB44B
        
- platform: template
  name: "Subtitle"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF00
        command: 0xE01F
        
- platform: template
  name: "YouTube"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF00
        command: 0x55AA
        
- platform: template
  name: "Netflix"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF00
        command: 0xD22D
        
- platform: template
  name: "Guide"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBF00
        command: 0xE21D
        