
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0586
        command: 0xF00F
        
- platform: template
  name: "Ok"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0586
        command: 0xE718
        
- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0586
        command: 0xBD42
        
- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0586
        command: 0xBC43
        
- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0586
        command: 0xE916
        
- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0586
        command: 0xEA15
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0586
        command: 0xF30C
        
- platform: template
  name: "V_down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0586
        command: 0xF20D
        
- platform: template
  name: "Back"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0586
        command: 0xE41B
        
- platform: template
  name: "Home"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0586
        command: 0xEB14
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xF609
        
- platform: template
  name: "Netflix"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xB34C
        
- platform: template
  name: "Hulu"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xA35C
        
- platform: template
  name: "Sleep"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xE51A
        
- platform: template
  name: "Opt"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xF30C
        
- platform: template
  name: "Return"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xBE41
        
- platform: template
  name: "Seek_fwd"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xA45B
        
- platform: template
  name: "Rewind"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xB04F
        
- platform: template
  name: "Play"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xBD42
        