
- platform: template
  name: "POWER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xFF00
        
- platform: template
  name: "OFF"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xFE01
        
- platform: template
  name: "Reset"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xFD02
        
- platform: template
  name: "Cool"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xFB04
        
- platform: template
  name: "Soft"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xFA05
        
- platform: template
  name: "Warm"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF906
        
- platform: template
  name: "DIM_UP"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xFC03
        
- platform: template
  name: "DIM_DOWN"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF807
        
- platform: template
  name: "RED"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF708
        
- platform: template
  name: "Light_RED"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF609
        
- platform: template
  name: "Orange"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF50A
        
- platform: template
  name: "Yellow"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF40B
        
- platform: template
  name: "Green"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF30C
        
- platform: template
  name: "Light_Green"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF20D
        
- platform: template
  name: "Light_Blue"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF10E
        
- platform: template
  name: "Cyan"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF00F
        
- platform: template
  name: "Blue"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xEF10
        
- platform: template
  name: "Dark_Blue"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xEE11
        
- platform: template
  name: "Purple"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xED12
        
- platform: template
  name: "Pink"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xEC13
        
- platform: template
  name: "Flash"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xEB14
        
- platform: template
  name: "Strobe"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xEA15
        
- platform: template
  name: "Fade"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xE916
        
- platform: template
  name: "Smooth"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xE817
        