
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x0C
    
- platform: template
  name: "Guide"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x2F
    
- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x14
    
- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x13
    
- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x15
    
- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x16
    
- platform: template
  name: "Ok"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x35
    
- platform: template
  name: "Ch_next"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x20
    
- platform: template
  name: "Ch_prev"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x21
    
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x10
    
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x11
    
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x01
        command: 0x0D
    