
- platform: template
  name: "POWER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xE31C
        
- platform: template
  name: "PLAY-PAUSE"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xFC03
        
- platform: template
  name: "BT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xE01F
        
- platform: template
  name: "VOL+"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xFF00
        
- platform: template
  name: "VOL-"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xFB04
        
- platform: template
  name: "MODE"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xE718
        
- platform: template
  name: "STOP"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xE817
        
- platform: template
  name: "FM_CH"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF906
        
- platform: template
  name: "CD"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF807
        
- platform: template
  name: "USB"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xFA05
        
- platform: template
  name: "SCAN"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xE916
        
- platform: template
  name: "NEXT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xFD02
        
- platform: template
  name: "PREV"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xFE01
        
- platform: template
  name: "REPEAT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF40B
        
- platform: template
  name: "A-B"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF00F
        
- platform: template
  name: "LEFT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xE51A
        
- platform: template
  name: "RIGHT"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xE619
        
- platform: template
  name: "AUX"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xEC13
        
- platform: template
  name: "1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF708
        
- platform: template
  name: "2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF609
        
- platform: template
  name: "3"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF50A
        
- platform: template
  name: "4"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF30C
        
- platform: template
  name: "5"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF20D
        
- platform: template
  name: "6"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xF10E
        
- platform: template
  name: "7"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xEF10
        
- platform: template
  name: "8"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xEE11
        
- platform: template
  name: "9"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xED12
        
- platform: template
  name: "0"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xEB14
        
- platform: template
  name: "OFF_TIMER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xEA15
        