
- platform: template
  name: "POWER_OFF"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8C37
        command: 0xFE01
        
- platform: template
  name: "POWER_ON"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8C37
        command: 0xFD02
        
- platform: template
  name: "IN_1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8C37
        command: 0xFA05
        
- platform: template
  name: "IN_3"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8C37
        command: 0xF906
        
- platform: template
  name: "IN_8"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8C37
        command: 0xF807
        
- platform: template
  name: "IN_2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8C37
        command: 0xF609
        
- platform: template
  name: "IN_7"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8C37
        command: 0xF40B
        
- platform: template
  name: "IN_4"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8C37
        command: 0xF20D
        
- platform: template
  name: "IN_5"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8C37
        command: 0xF00F
        
- platform: template
  name: "IN_6"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8C37
        command: 0xB54A
        
- platform: template
  name: "D-IN"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8C37
        command: 0xA55A
        
- platform: template
  name: "IN_9"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8C37
        command: 0x916E
        
- platform: template
  name: "Unknown"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8C37
        command: 0x916E
        