
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xF708
        
- platform: template
  name: "Back"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xFB04
        
- platform: template
  name: "Home"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xBC43
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xFD02
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xFC03
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xF609
        
- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xA956
        
- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xA857
        
- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xA758
        
- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xA659
        
- platform: template
  name: "Ok"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xA55A
        
- platform: template
  name: "Again"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xBE41
        
- platform: template
  name: "Sleep"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xE51A
        
- platform: template
  name: "Star"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xF30C
        
- platform: template
  name: "Rewind"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xB04F
        
- platform: template
  name: "Play_pause"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xBD42
        
- platform: template
  name: "Fast_forward"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xA45B
        
- platform: template
  name: "Netflix"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xB34C
        
- platform: template
  name: "Hulu"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xA35C
        
- platform: template
  name: "Sling"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0xBA45
        
- platform: template
  name: "Now"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFB04
        command: 0x9867
        