
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x0C
    
- platform: template
  name: "Input"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x28
    
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x0D
    
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x10
    
- platform: template
  name: "Vol_dwn"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x11
    