
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x0C
    
- platform: template
  name: "Menu"
  on_press:
    - remote_transmitter.transmit_raw:
        carrier_frequency: 38kHz
        code: [762, -983, 1673, -1001, 764, -947, 819, -975, 791, -974, 791, -973, 792, -1855, 1676, -1854, 792, -974, 792, -974, 1674, -89718, 762, -977, 1671, -1002, 763, -974, 791, -1002, 763, -1002, 763, -976, 790, -1884, 1646, -1856, 791, -1002, 763, -1003, 1646, -89745, 735, -1030, 1618, -1030, 735, -1004, 762, -1003, 762, -976, 790, -1003, 762, -1886, 1645, -1857, 790, -1004, 761, -976, 1672]
    
- platform: template
  name: "Guide"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x3E
    
- platform: template
  name: "Info"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x0F
    
- platform: template
  name: "Exit"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x0F
    
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x0D
    
- platform: template
  name: "Input"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x38
    
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x10
    
- platform: template
  name: "Vol_down"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x11
    
- platform: template
  name: "Channel_up"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x20
    
- platform: template
  name: "Channel_down"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x21
    
- platform: template
  name: "Prev_Channel"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x22
    
- platform: template
  name: "OK"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x2B
    
- platform: template
  name: "1"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x01
    
- platform: template
  name: "2"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x02
    
- platform: template
  name: "3"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x03
    
- platform: template
  name: "4"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x04
    
- platform: template
  name: "5"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x05
    
- platform: template
  name: "6"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x06
    
- platform: template
  name: "7"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x07
    
- platform: template
  name: "8"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x08
    
- platform: template
  name: "9"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x09
    
- platform: template
  name: "0"
  on_press:
    - remote_transmitter.transmit_rc5:
        address: 0x00
        command: 0x00
    