
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xCF30
        command: 0x738C
        
- platform: template
  name: "Mode"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xCF30
        command: 0x7887
        
- platform: template
  name: "Timer"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xCF30
        command: 0x7986
        
- platform: template
  name: "Oscy"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xCF30
        command: 0x639C
        
- platform: template
  name: "Oscx"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xCF30
        command: 0x6A95
        
- platform: template
  name: "Slower"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xCF30
        command: 0x7C83
        
- platform: template
  name: "Faster"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xCF30
        command: 0x7A85
        