
- platform: template
  name: "On_off"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0xA90
        nbits: 12

- platform: template
  name: "Netflix"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x1F58
        nbits: 15

- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x2F0
        nbits: 12

- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0xAF0
        nbits: 12

- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x2D0
        nbits: 12

- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0xCD0
        nbits: 12

- platform: template
  name: "Ok"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0xA70
        nbits: 12

- platform: template
  name: "Back"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x62E9
        nbits: 15

- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x490
        nbits: 12

- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0xC90
        nbits: 12

- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x290
        nbits: 12

- platform: template
  name: "Home"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x70
        nbits: 12

- platform: template
  name: "Hdmi"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0xA50
        nbits: 12
