
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0xA90
        nbits: 12

- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x290
        nbits: 12

- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x490
        nbits: 12

- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0xC90
        nbits: 12

- platform: template
  name: "Ch_next"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x90
        nbits: 12

- platform: template
  name: "Ch_prev"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x890
        nbits: 12

- platform: template
  name: "Display"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x5D0
        nbits: 12

- platform: template
  name: "1"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x10
        nbits: 12

- platform: template
  name: "2"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x810
        nbits: 12

- platform: template
  name: "3"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x410
        nbits: 12

- platform: template
  name: "4"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0xC10
        nbits: 12

- platform: template
  name: "5"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x210
        nbits: 12

- platform: template
  name: "6"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0xA10
        nbits: 12

- platform: template
  name: "7"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x610
        nbits: 12

- platform: template
  name: "8"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0xE10
        nbits: 12

- platform: template
  name: "9"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x110
        nbits: 12

- platform: template
  name: "Period"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x5CE9
        nbits: 15

- platform: template
  name: "0"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x910
        nbits: 12

- platform: template
  name: "Ent"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0xD10
        nbits: 12

- platform: template
  name: "Freeze"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x3B0
        nbits: 12

- platform: template
  name: "Cc"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x425
        nbits: 15

- platform: template
  name: "Sleep"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x6D0
        nbits: 12

- platform: template
  name: "Jump"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0xDD0
        nbits: 12

- platform: template
  name: "Dmex"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x6B58
        nbits: 15

- platform: template
  name: "Sound"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x6FE9
        nbits: 15

- platform: template
  name: "Picture"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x270
        nbits: 12

- platform: template
  name: "Wide"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x5E25
        nbits: 15

- platform: template
  name: "Favorites"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x37EE
        nbits: 15

- platform: template
  name: "Input"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0xA50
        nbits: 12

- platform: template
  name: "Return"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x62E9
        nbits: 15

- platform: template
  name: "Options"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x36E9
        nbits: 15

- platform: template
  name: "Home"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x70
        nbits: 12

- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x2F0
        nbits: 12

- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x2D0
        nbits: 12

- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0xCD0
        nbits: 12

- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0xAF0
        nbits: 12

- platform: template
  name: "Prev"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x1EE9
        nbits: 15

- platform: template
  name: "Replay"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x4FE9
        nbits: 15

- platform: template
  name: "Advance"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0xFE9
        nbits: 15

- platform: template
  name: "Next"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x5EE9
        nbits: 15

- platform: template
  name: "Rewind"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x6CE9
        nbits: 15

- platform: template
  name: "Play"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x2CE9
        nbits: 15

- platform: template
  name: "Fast_fwd"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x1CE9
        nbits: 15

- platform: template
  name: "Theater"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x3EE
        nbits: 15

- platform: template
  name: "Pause"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x4CE9
        nbits: 15

- platform: template
  name: "Stop"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0xCE9
        nbits: 15
