
- platform: template
  name: "B_REV"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8484
        command: 0xF609
        
- platform: template
  name: "B_ZOOM_WIDE"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8484
        command: 0xF50A
        
- platform: template
  name: "B_ZOOM_TELE"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8484
        command: 0xF40B
        
- platform: template
  name: "B_FWD"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8484
        command: 0xF30C
        
- platform: template
  name: "B_IRIS_CLOSE"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8484
        command: 0xF20D
        
- platform: template
  name: "B_ZERO_RESET_FWD"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8484
        command: 0xF10E
        
- platform: template
  name: "B_ZERO_RESET_REV"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8484
        command: 0xF00F
        
- platform: template
  name: "B_FOCUS_F"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8484
        command: 0xEE11
        
- platform: template
  name: "B_FOCUS_N"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8484
        command: 0xED12
        
- platform: template
  name: "B_LAMP_ON"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8484
        command: 0xEC13
        
- platform: template
  name: "B_LAMP_OFF"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8484
        command: 0xEB14
        
- platform: template
  name: "B_IRIS_OPEN"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x8484
        command: 0x1FE0
        