
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0xA8B47
        nbits: 20

- platform: template
  name: "Eject"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x68B47
        nbits: 20

- platform: template
  name: "Menu"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x94B47
        nbits: 20

- platform: template
  name: "Prev"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0xC2B47
        nbits: 20

- platform: template
  name: "Ok"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0xBCB47
        nbits: 20

- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x9CB47
        nbits: 20

- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x5CB47
        nbits: 20

- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0xDCB47
        nbits: 20

- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x3CB47
        nbits: 20

- platform: template
  name: "Fast_fo"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x38B47
        nbits: 20

- platform: template
  name: "Fast_ba"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0xD8B47
        nbits: 20

- platform: template
  name: "Pause"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x98B47
        nbits: 20

- platform: template
  name: "Play"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x58B47
        nbits: 20

- platform: template
  name: "Stop"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x18B47
        nbits: 20

- platform: template
  name: "Subtitle"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0xC6B47
        nbits: 20

- platform: template
  name: "Audio"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x26B47
        nbits: 20

- platform: template
  name: "PopUp"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x94B47
        nbits: 20

- platform: template
  name: "Top_menu"
  on_press:
    - remote_transmitter.transmit_sony:
        data: 0x34B47
        nbits: 20
