
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBF40
        
- platform: template
  name: "Ok"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x718E
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBE41
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBA45
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB748
        
- platform: template
  name: "Next"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x748B
        
- platform: template
  name: "Previous"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x758A
        
- platform: template
  name: "Bluetooth_mode"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xDD22
        
- platform: template
  name: "Bt_pair"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x906F
        
- platform: template
  name: "Source"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xDD22
        
- platform: template
  name: "Setup_Info"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xE41B
        
- platform: template
  name: "Height On"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x06F9
        
- platform: template
  name: "Height Off"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x05FA
        
- platform: template
  name: "Night On"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x9E61
        
- platform: template
  name: "Night Off"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x9D62
        
- platform: template
  name: "TruVol On"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xD728
        
- platform: template
  name: "TruVol Off"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBD42
        
- platform: template
  name: "VirtX On"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x7A85
        
- platform: template
  name: "VirtX Off"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x5CA3
        
- platform: template
  name: "Bass +"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x946B
        
- platform: template
  name: "Bass -"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x956A
        
- platform: template
  name: "Treble +"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x9669
        
- platform: template
  name: "Treble -"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x9768
        
- platform: template
  name: "Dialogue +"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x20DF
        
- platform: template
  name: "Dialogue -"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x1FE0
        
- platform: template
  name: "Center +"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x8F70
        
- platform: template
  name: "Center -"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x8F70
        
- platform: template
  name: "Subwoofer +"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB24D
        
- platform: template
  name: "Subwoofer -"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xAE51
        
- platform: template
  name: "Surr lvl +"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x926D
        
- platform: template
  name: "Surr lvl -"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x936C
        
- platform: template
  name: "Surr bal +"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x4CB3
        
- platform: template
  name: "Surr bal -"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x4BB4
        
- platform: template
  name: "Height lvl +"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x4FB0
        
- platform: template
  name: "Height lvl -"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x5FA0
        
- platform: template
  name: "EcoPower On"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x718E
        
- platform: template
  name: "EcoPower Off"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xD827
        
- platform: template
  name: "PowerLED On"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xDF20
        
- platform: template
  name: "PowerLED Off"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xDE21
        
- platform: template
  name: "AV Delay +"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x29D6
        
- platform: template
  name: "AV Delay -"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x8E71
        
- platform: template
  name: "Speaker Test"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x53AC
        
- platform: template
  name: "EQ Music"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x9966
        
- platform: template
  name: "EQ Movie"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x9867
        
- platform: template
  name: "EQ Direct"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x738C
        
- platform: template
  name: "EQ Game"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x1EE1
        
- platform: template
  name: "Bluetooth_input"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xDD22
        
- platform: template
  name: "Last Input"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x55AA
        
- platform: template
  name: "USB"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x5EA1
        
- platform: template
  name: "AUX"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x4EB1
        
- platform: template
  name: "AUX_VA"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x4DB2
        
- platform: template
  name: "Optical"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x37C8
        
- platform: template
  name: "HDMI in"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x54AB
        
- platform: template
  name: "HDMI-eARC"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x659A
        
- platform: template
  name: "Surr Dual"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x649B
        
- platform: template
  name: "Surr On"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xDC23
        
- platform: template
  name: "Surr Off"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xDB24
        