
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBE41
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_raw:
        carrier_frequency: 38kHz
        code: [9062, -4432, 680, -451, 625, -506, 625, -505, 625, -505, 625, -506, 624, -507, 623, -531, 599, -531, 599, -1633, 623, -1657, 599, -1657, 624, -1632, 624, -1633, 623, -1634, 597, -1659, 622, -1635, 620, -1636, 620, -510, 596, -1659, 597, -534, 621, -509, 597, -534, 597, -1659, 597, -534, 596, -534, 596, -1659, 597, -534, 596, -1659, 597, -1660, 621, -1635, 621, -509, 597, -1658, 596]
    
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBF40
        
- platform: template
  name: "Input"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBB44
        
- platform: template
  name: "Prev"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x758A
        
- platform: template
  name: "Play_Pause"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x718E
        
- platform: template
  name: "Next"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x748B
        
- platform: template
  name: "TV_Vol"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB34C
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB748
        
- platform: template
  name: "VRTiX"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xAF50
        
- platform: template
  name: "Bass"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFD02
        
- platform: template
  name: "Eq"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0x9966
        
- platform: template
  name: "Treb"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xFC03
        