
- platform: template
  name: "POWER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xAE51
        
- platform: template
  name: "Mouse"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xAD52
        
- platform: template
  name: "Ok"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF20D
        
- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xD926
        
- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xD728
        
- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xDA25
        
- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xD827
        
- platform: template
  name: "Menu"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xB649
        
- platform: template
  name: "Back"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xE41B
        
- platform: template
  name: "Home"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xAC53
        
- platform: template
  name: "Minus"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xA956
        
- platform: template
  name: "Plus"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xB14E
        