
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBD45
        command: 0xED12
        
- platform: template
  name: "Input"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBD45
        command: 0x15EA
        
- platform: template
  name: "Pause"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBD45
        command: 0xE01F
        
- platform: template
  name: "Play"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBD45
        command: 0xE01F
        
- platform: template
  name: "Stop"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBD45
        command: 0xE01F
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBD45
        command: 0x42BD
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBD45
        command: 0x9F60
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xBD45
        command: 0x9E61
        