
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x1D0A
        command: 0xFE01
        
- platform: template
  name: "Bt"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x1D0A
        command: 0xFD02
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x1D0A
        command: 0xFC03
        
- platform: template
  name: "Source"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x1D0A
        command: 0xFB04
        
- platform: template
  name: "Distance"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x1D0A
        command: 0xFA05
        
- platform: template
  name: "Ppl"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x1D0A
        command: 0xF906
        
- platform: template
  name: "Sub_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x1D0A
        command: 0xF807
        
- platform: template
  name: "Sub_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x1D0A
        command: 0xF609
        
- platform: template
  name: "Bass_boost"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x1D0A
        command: 0xE21D
        
- platform: template
  name: "Preset"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x1D0A
        command: 0xEC13
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x1D0A
        command: 0xF708
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x1D0A
        command: 0xF50A
        
- platform: template
  name: "Preset_1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x1D0A
        command: 0xF40B
        
- platform: template
  name: "Preset_2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x1D0A
        command: 0xF30C
        
- platform: template
  name: "Preset_3"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x1D0A
        command: 0xF20D
        
- platform: template
  name: "Movie"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x1D0A
        command: 0xF10E
        
- platform: template
  name: "Game"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x1D0A
        command: 0xF00F
        
- platform: template
  name: "Music"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x1D0A
        command: 0xEF10
        