
- platform: template
  name: "POWER"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF30C
        
- platform: template
  name: "Hdmi_1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFE01
        
- platform: template
  name: "Hdmi_2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFC03
        
- platform: template
  name: "Hdmi_3"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF807
        
- platform: template
  name: "Hdmi_4"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF609
        
- platform: template
  name: "Hdmi_5"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF20D
        