
- platform: template
  name: "Source_1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xED12
        
- platform: template
  name: "Source_2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xE11E
        
- platform: template
  name: "Source_3"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFD02
        
- platform: template
  name: "Next_Source"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF708
        
- platform: template
  name: "Prev_Source"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xE41B
        