
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0x7D82
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0x609F
        
- platform: template
  name: "Vol_dn"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0x748B
        
- platform: template
  name: "Ch_next"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0x649B
        
- platform: template
  name: "Ch_prev"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0x708F
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0x2FD0
        