
- platform: template
  name: "Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0E86
        command: 0xED12
        
- platform: template
  name: "Menu"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0E86
        command: 0xEB14
        
- platform: template
  name: "Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0E86
        command: 0xF40B
        
- platform: template
  name: "Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0E86
        command: 0xF30C
        
- platform: template
  name: "Ok"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0E86
        command: 0xEA15
        
- platform: template
  name: "Left"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0E86
        command: 0xE41B
        
- platform: template
  name: "Right"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0E86
        command: 0xE31C
        
- platform: template
  name: "Vol_up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0E86
        command: 0xF20D
        
- platform: template
  name: "Vol_down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0E86
        command: 0xF10E
        
- platform: template
  name: "Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x0E86
        command: 0xF00F
        